2019-11-11 14:02:53,023 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_0, 一共：0条
2019-11-11 14:03:11,361 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_1, 一共：0条
2019-11-11 14:03:22,006 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_0, 一共：0条
2019-11-11 14:03:32,533 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_1, 一共：0条
2019-11-11 14:03:49,376 - webcrawer service - INFO - 运行成功: taipingyangbaoxian_3_3_0, 一共：0条
2019-11-11 14:04:03,662 - webcrawer service - INFO - 运行成功: tianjinshizhengfucaigoupingtai_3_4, 一共：0条
2019-11-11 14:04:13,469 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_0, 一共：0条
2019-11-11 14:04:24,057 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_1, 一共：0条
2019-11-11 14:04:39,148 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_0, 一共：0条
2019-11-11 14:05:06,235 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_1, 一共：0条
2019-11-11 14:07:47,768 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_0, 一共：6条
2019-11-11 14:08:56,360 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_1, 一共：2条
2019-11-11 14:09:26,705 - webcrawer service - INFO - 运行成功: shanghaigonggongziyuanjiaoyiwang_3_14, 一共：0条
2019-11-11 14:09:48,250 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_0, 一共：0条
2019-11-11 14:10:11,299 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_1, 一共：0条
2019-11-11 14:10:30,971 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_0, 一共：0条
2019-11-11 14:10:50,626 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_1, 一共：0条
2019-11-11 14:11:13,126 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_0, 一共：0条
2019-11-11 14:11:46,382 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_1, 一共：0条
2019-11-11 14:12:06,695 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_0, 一共：0条
2019-11-11 14:12:22,365 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_1, 一共：0条
2019-11-11 14:12:55,580 - webcrawer service - INFO - 运行成功: hainanshenggonggongziyuanjiaoyiwang_3_20, 一共：0条
2019-11-11 14:13:34,719 - webcrawer service - INFO - 运行成功: anzhaocai_3_23, 一共：0条
2019-11-11 14:13:45,705 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_0, 一共：0条
2019-11-11 14:14:04,688 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_1, 一共：0条
2019-11-11 14:14:23,865 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-11 14:14:43,173 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-11 14:14:52,893 - webcrawer service - INFO - 运行成功: chongqingguojitouzizixunjituanyouxiangongsi_3_27, 一共：0条
2019-11-11 14:15:10,719 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_0, 一共：0条
2019-11-11 14:15:21,281 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_1, 一共：0条
2019-11-11 14:15:45,938 - webcrawer service - INFO - 运行成功: chengdushigonggongziyuanjiaoyizhongxin_3_29, 一共：0条
2019-11-11 14:16:01,313 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_0, 一共：0条
2019-11-11 14:16:22,109 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_1, 一共：0条
2019-11-11 14:16:38,252 - webcrawer service - INFO - 运行成功: bingtuanzhengfucaigouwang_3_32, 一共：0条
2019-11-11 14:22:59,429 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_0, 一共：1条
2019-11-11 14:23:26,726 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_1, 一共：0条
2019-11-11 14:29:45,643 - webcrawer service - INFO - 运行成功: hebeizhaobiaocaigouwang_3_9, 一共：3条
2019-11-11 14:33:26,455 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_0, 一共：2条
2019-11-11 14:36:05,063 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_1, 一共：0条
2019-11-11 14:40:32,018 - webcrawer service - INFO - 运行成功: liaoningshengcaigouzhaobiaowang_3_12_0, 一共：6条
2019-11-11 14:44:19,939 - webcrawer service - INFO - 运行成功: liaoningshengcaigouzhaobiaowang_3_12_1, 一共：0条
2019-11-11 14:45:41,582 - webcrawer service - INFO - 运行成功: dalianshizhaobiaowang_3_13, 一共：0条
2019-11-11 14:48:01,892 - webcrawer service - INFO - 运行成功: shenzhenqinglima_3_21_0, 一共：1条
2019-11-11 14:48:53,526 - webcrawer service - INFO - 运行成功: shenzhenqinglima_3_21_1, 一共：0条
2019-11-11 14:49:02,923 - webcrawer service - INFO - 运行成功: chongqingguojitouzizixun_3_26, 一共：0条
2019-11-11 15:42:18,187 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_0, 一共：0条
2019-11-11 15:42:35,205 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_1, 一共：0条
2019-11-11 15:42:44,796 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_0, 一共：0条
2019-11-11 15:42:53,891 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_1, 一共：0条
2019-11-11 15:43:10,047 - webcrawer service - INFO - 运行成功: taipingyangbaoxian_3_3_0, 一共：0条
2019-11-11 15:44:11,125 - webcrawer service - INFO - 运行成功: tianjinshizhengfucaigoupingtai_3_4, 一共：0条
2019-11-11 15:44:20,797 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_0, 一共：0条
2019-11-11 15:44:32,095 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_1, 一共：0条
2019-11-11 15:44:45,995 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_0, 一共：0条
2019-11-11 15:45:07,610 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_1, 一共：0条
2019-11-11 15:47:43,109 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_0, 一共：6条
2019-11-11 15:49:00,969 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_1, 一共：2条
2019-11-11 15:49:28,871 - webcrawer service - INFO - 运行成功: shanghaigonggongziyuanjiaoyiwang_3_14, 一共：0条
2019-11-11 15:49:55,359 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_0, 一共：0条
2019-11-11 15:50:16,031 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_1, 一共：0条
2019-11-11 15:50:45,735 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_0, 一共：0条
2019-11-11 15:51:13,375 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_1, 一共：0条
2019-11-11 15:51:41,543 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_0, 一共：0条
2019-11-11 15:52:03,050 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_1, 一共：0条
2019-11-11 15:52:22,283 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_0, 一共：0条
2019-11-11 15:52:41,767 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_1, 一共：0条
2019-11-11 15:53:08,891 - webcrawer service - INFO - 运行成功: hainanshenggonggongziyuanjiaoyiwang_3_20, 一共：0条
2019-11-11 15:53:45,344 - webcrawer service - INFO - 运行成功: anzhaocai_3_23, 一共：0条
2019-11-11 15:53:57,130 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_0, 一共：0条
2019-11-11 15:54:18,486 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_1, 一共：0条
2019-11-11 15:54:31,262 - webcrawer service - ERROR - 运行失败: yunnanshengzhengfucaigouwang_3_26_0
2019-11-11 15:54:31,372 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 126, in RunMain
    html_str = model.parse_url("",url_type=url_info["type"],url_params=url_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 156, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 系统异常请联系管理员！
Message: unexpected alert open: {Alert text : 系统异常请联系管理员！}
  (Session info: chrome=76.0.3809.87)


2019-11-11 15:54:49,368 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-11 15:54:59,531 - webcrawer service - INFO - 运行成功: chongqingguojitouzizixunjituanyouxiangongsi_3_27, 一共：0条
2019-11-11 15:55:16,953 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_0, 一共：0条
2019-11-11 15:55:27,391 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_1, 一共：0条
2019-11-11 15:55:56,413 - webcrawer service - INFO - 运行成功: chengdushigonggongziyuanjiaoyizhongxin_3_29, 一共：0条
2019-11-11 15:56:10,157 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_0, 一共：0条
2019-11-11 15:56:30,303 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_1, 一共：0条
2019-11-11 15:56:45,966 - webcrawer service - INFO - 运行成功: bingtuanzhengfucaigouwang_3_32, 一共：0条
2019-11-11 16:03:07,609 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_0, 一共：1条
2019-11-11 16:03:34,051 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_1, 一共：0条
2019-11-11 16:04:12,612 - webcrawer service - INFO - 运行成功: hebeizhaobiaocaigouwang_3_9, 一共：0条
2019-11-11 16:13:17,223 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_0, 一共：0条
2019-11-11 16:15:20,594 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_0, 一共：0条
2019-11-11 16:15:38,391 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_1, 一共：0条
2019-11-11 16:19:49,751 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_0, 一共：6条
2019-11-11 16:21:12,777 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_1, 一共：2条
2019-11-11 16:23:10,643 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_0, 一共：0条
2019-11-11 16:23:30,564 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_1, 一共：0条
2019-11-11 16:26:33,657 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_0, 一共：6条
2019-11-11 16:27:57,281 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_1, 一共：2条
2019-11-11 16:30:19,062 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_0, 一共：0条
2019-11-11 16:30:35,765 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_1, 一共：0条
2019-11-11 16:30:44,854 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_0, 一共：0条
2019-11-11 16:30:53,734 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_1, 一共：0条
2019-11-11 16:31:09,859 - webcrawer service - INFO - 运行成功: taipingyangbaoxian_3_3_0, 一共：0条
2019-11-11 16:32:22,282 - webcrawer service - INFO - 运行成功: tianjinshizhengfucaigoupingtai_3_4, 一共：0条
2019-11-11 16:32:31,937 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_0, 一共：0条
2019-11-11 16:32:41,265 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_1, 一共：0条
2019-11-11 16:32:52,563 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_0, 一共：0条
2019-11-11 16:33:08,937 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_1, 一共：0条
2019-11-11 16:36:02,189 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_0, 一共：6条
2019-11-11 16:37:59,750 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_1, 一共：2条
2019-11-11 16:38:29,454 - webcrawer service - INFO - 运行成功: shanghaigonggongziyuanjiaoyiwang_3_14, 一共：0条
2019-11-11 16:38:51,408 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_0, 一共：0条
2019-11-11 16:39:14,187 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_1, 一共：0条
2019-11-11 16:39:49,253 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_0, 一共：0条
2019-11-11 16:40:24,281 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_1, 一共：0条
2019-11-11 16:41:24,466 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_0, 一共：0条
2019-11-11 16:41:49,150 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_1, 一共：0条
2019-11-11 16:42:19,221 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_0, 一共：0条
2019-11-11 16:42:40,684 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_1, 一共：0条
2019-11-11 16:43:09,928 - webcrawer service - INFO - 运行成功: hainanshenggonggongziyuanjiaoyiwang_3_20, 一共：0条
2019-11-11 16:43:46,604 - webcrawer service - INFO - 运行成功: anzhaocai_3_23, 一共：0条
2019-11-11 16:43:57,292 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_0, 一共：0条
2019-11-11 16:44:18,437 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_1, 一共：0条
2019-11-11 16:44:43,949 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-11 16:45:00,605 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-11 16:45:15,500 - webcrawer service - INFO - 运行成功: chongqingguojitouzizixunjituanyouxiangongsi_3_27, 一共：0条
2019-11-11 16:45:44,828 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_0, 一共：0条
2019-11-11 16:45:56,861 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_1, 一共：0条
2019-11-11 16:46:37,703 - webcrawer service - INFO - 运行成功: chengdushigonggongziyuanjiaoyizhongxin_3_29, 一共：0条
2019-11-11 16:46:54,355 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_0, 一共：0条
2019-11-11 16:47:14,549 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_1, 一共：0条
2019-11-11 16:47:30,405 - webcrawer service - INFO - 运行成功: bingtuanzhengfucaigouwang_3_32, 一共：0条
2019-11-11 16:54:45,719 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_0, 一共：1条
2019-11-11 16:55:27,722 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_1, 一共：0条
2019-11-11 17:06:36,695 - webcrawer service - INFO - 运行成功: hebeizhaobiaocaigouwang_3_9, 一共：3条
2019-11-11 17:12:24,845 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_0, 一共：2条
2019-11-11 17:16:08,922 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_1, 一共：0条
2019-11-11 17:24:25,705 - webcrawer service - INFO - 运行成功: liaoningshengcaigouzhaobiaowang_3_12_0, 一共：6条
2019-11-11 17:24:40,243 - webcrawer service - ERROR - 运行失败: liaoningshengcaigouzhaobiaowang_3_12_1
2019-11-11 17:24:40,330 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 109, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 78, in model_log_in_web
    WebDriverWait(driver, 10, 0.5).until(EC.presence_of_element_located((By.ID, param["name"])))
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 64, in __call__
    return _find_element(driver, self.locator)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer
  (Session info: chrome=76.0.3809.87)


2019-11-11 17:30:28,718 - webcrawer service - INFO - 运行成功: dalianshizhaobiaowang_3_13, 一共：0条
2019-11-11 18:23:48,929 - webcrawer service - ERROR - 运行失败: shenzhenqinglima_3_21_0
2019-11-11 18:23:48,929 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 129, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 22, in getUrlList
    ori_number = model.number_page(parame["number_xpath"], html_str)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 520, in number_page
    number = html_element.xpath(number_xpath)
AttributeError: 'NoneType' object has no attribute 'xpath'

2019-11-11 18:25:23,752 - webcrawer service - INFO - 运行成功: shenzhenqinglima_3_21_1, 一共：0条
2019-11-11 18:25:59,861 - webcrawer service - ERROR - 运行失败: chongqingguojitouzizixun_3_26
2019-11-11 18:25:59,861 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 106, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 86, in getUrlList
    html_str = model.parse_url("",url_type=original_url,url_params=tmp_parame)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 156, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="Paging"]/div/div/table/tbody/tr/td[text()=6]"}
  (Session info: chrome=76.0.3809.87)


2019-11-13 11:20:36,038 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-13 11:20:36,448 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 115, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 93, in model_log_in_web
    if login_info["params"]["captcha"] :
TypeError: list indices must be integers or slices, not str

2019-11-13 11:24:16,783 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-13 11:24:17,220 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 115, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 94, in model_log_in_web
    capt = utils.get_image_captcha()
TypeError: get_image_captcha() missing 1 required positional argument: 'self'

2019-11-13 13:44:58,733 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-13 13:44:59,166 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 158, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 98, in model_log_in_web
    capt = utils.get_image_captcha()
TypeError: get_image_captcha() missing 1 required positional argument: 'self'

2019-11-13 13:50:28,634 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-13 13:50:29,081 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 158, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 98, in model_log_in_web
    capt = get_image_captcha(driver)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 134, in get_image_captcha
    top, bottom, left, right = get_position(driver)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 112, in get_position
    img = WebDriverWait(driver, 10, 0.5).wait.until(EC.presence_of_element_located((By.CLASS_NAME, 'rzmimg')))
AttributeError: 'WebDriverWait' object has no attribute 'wait'

2019-11-13 13:53:31,464 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-13 13:53:32,211 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 158, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 98, in model_log_in_web
    capt = get_image_captcha(driver)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 134, in get_image_captcha
    top, bottom, left, right = get_position(driver)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 112, in get_position
    img = WebDriverWait(driver, 10, 0.5).until(EC.presence_of_element_located((By.CLASS_NAME, 'rzmimg')))
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2019-11-13 14:33:33,583 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-13 14:33:33,585 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 158, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 99, in model_log_in_web
    driver.find_element_by_id(login_info["params"]["captcha"]).send_keys(capt)
TypeError: list indices must be integers or slices, not str

2019-11-13 14:39:39,902 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-13 14:39:39,904 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 158, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 99, in model_log_in_web
    driver.find_element_by_id(login_info["captcha"]).send_keys(capt)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="topLoginRand"]"}
  (Session info: chrome=76.0.3809.87)


2019-11-13 14:43:33,557 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-13 14:43:33,559 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 158, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 101, in model_log_in_web
    driver.find_element_by_xpath(login_info["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="loginErrForm"]/span[6]/input"}
  (Session info: chrome=76.0.3809.87)


2019-11-13 14:52:27,171 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-13 14:52:27,172 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 158, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 101, in model_log_in_web
    driver.find_element_by_class(login_info["button"]).click()
AttributeError: 'WebDriver' object has no attribute 'find_element_by_class'

2019-11-13 14:59:36,495 - webcrawer service - INFO - 运行成功: ningxiazhaobiaowang_3_30_1, 一共：5条
2019-11-13 15:28:34,286 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-13 15:28:34,371 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 188, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 104, in model_log_in_web
    driver.find_element_by_class_name(captcha["name"]).send_keys(capt)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".yzm"}
  (Session info: chrome=76.0.3809.87)


2019-11-13 15:32:39,446 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-13 15:32:39,448 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 188, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 115, in model_log_in_web
    driver.find_element_by_id(button["name"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="btn01"]"}
  (Session info: chrome=76.0.3809.87)


2019-11-13 15:51:02,530 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_1
2019-11-13 15:51:02,531 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 188, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 102, in model_log_in_web
    driver.find_element_by_id(captcha["name"]).send_keys(capt)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="yzm"]"}
  (Session info: chrome=76.0.3809.87)


2019-11-13 15:55:43,398 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_1
2019-11-13 15:55:43,400 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 188, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 117, in model_log_in_web
    driver.find_element_by_class_name(button["name"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn01"}
  (Session info: chrome=76.0.3809.87)


2019-11-13 16:07:56,037 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_1, 一共：81条
2019-11-13 16:31:03,555 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_1, 一共：81条
2019-11-13 16:43:30,114 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_1
2019-11-13 16:43:30,117 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 190, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 125, in model_log_in_web
    driver.find_elemnt_by_xpath("/html/body/div[3]/div[1]/div[1]/div/input")
AttributeError: 'WebDriver' object has no attribute 'find_elemnt_by_xpath'

2019-11-13 16:56:59,355 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_1, 一共：81条
2019-11-13 16:59:13,414 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_1
2019-11-13 16:59:13,494 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 190, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 83, in model_log_in_web
    WebDriverWait(driver, 10, 0.5).until(EC.presence_of_element_located((By.ID, param["name"])))
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 64, in __call__
    return _find_element(driver, self.locator)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=76.0.3809.87)


2019-11-13 17:00:35,648 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_1
2019-11-13 17:00:35,649 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 128, in RunMain
    html_str = model.parse_url("",url_type=parame["startPage"]["type"],url_params=parame["startPage"])
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 238, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div[1]/div[1]/div/input"}
  (Session info: chrome=76.0.3809.87)


2019-11-13 17:05:56,160 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_1
2019-11-13 17:05:56,163 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 128, in RunMain
    html_str = model.parse_url("",url_type=parame["startPage"]["type"],url_params=parame["startPage"])
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 238, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div[1]/div[1]/div/input"}
  (Session info: chrome=76.0.3809.87)


2019-11-13 17:07:12,781 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_1
2019-11-13 17:07:12,784 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 128, in RunMain
    html_str = model.parse_url("",url_type=parame["startPage"]["type"],url_params=parame["startPage"])
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 238, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div[1]/div[1]/div/input"}
  (Session info: chrome=76.0.3809.87)


2019-11-13 17:08:37,352 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_1
2019-11-13 17:08:37,355 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 128, in RunMain
    html_str = model.parse_url("",url_type=parame["startPage"]["type"],url_params=parame["startPage"])
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 238, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div[1]/div[1]/div/input"}
  (Session info: chrome=76.0.3809.87)


2019-11-13 17:35:14,888 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_1
2019-11-13 17:35:14,895 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 192, in log_in_web
    self.cookie_info = self.driver.get_cookies()                 # 列表中包含多个字典
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 841, in get_cookies
    return self.execute(Command.GET_ALL_COOKIES)['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 验证码错误，请重新输入验证码。
Message: unexpected alert open: {Alert text : 验证码错误，请重新输入验证码。}
  (Session info: chrome=76.0.3809.87)


2019-11-14 09:23:46,713 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_1, 一共：0条
2019-11-14 09:30:51,367 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_1
2019-11-14 09:30:51,464 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 145, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 95, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 186, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 83, in model_log_in_web
    WebDriverWait(driver, 10, 0.5).until(EC.presence_of_element_located((By.ID, param["name"])))
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2019-11-14 11:01:32,480 - webcrawer service - ERROR - 运行失败: heilongjiangzhaobiaowang_3_10_0
2019-11-14 11:01:32,511 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 97, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 134, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 98, in model_log_in_web
    driver.find_element_by_xpath(login_info["verifyCodexpath"]).send_keys(res)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='yzm']"}
  (Session info: chrome=76.0.3809.87)


2019-11-14 11:02:20,433 - webcrawer service - ERROR - 运行失败: heilongjiangzhaobiaowang_3_10_0
2019-11-14 11:02:20,433 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 97, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 134, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 98, in model_log_in_web
    driver.find_element_by_xpath(login_info["verifyCodexpath"]).send_keys(res)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='yzm']"}
  (Session info: chrome=76.0.3809.87)


2019-11-14 11:07:52,354 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_0, 一共：0条
2019-11-14 11:10:20,167 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_0, 一共：0条
2019-11-14 11:14:20,432 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_0, 一共：0条
2019-11-14 11:18:37,275 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_0, 一共：23条
2019-11-14 11:25:47,747 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_1, 一共：11条
2019-11-14 11:37:01,766 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_0, 一共：36条
2019-11-14 11:39:13,344 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_1
2019-11-14 11:39:13,497 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 97, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 134, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 103, in model_log_in_web
    driver.find_element_by_xpath(login_info["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'value' must be a string
  (Session info: chrome=76.0.3809.87)


2019-11-14 13:46:51,729 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_1, 一共：104条
2019-11-14 13:49:52,790 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_0
2019-11-14 13:49:52,879 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 97, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 134, in log_in_web
    self.driver = model_log_in_web(self.driver, url, login_info,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 103, in model_log_in_web
    driver.find_element_by_xpath(login_info["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="loginErrForm"]/span[6]/input"}
  (Session info: chrome=76.0.3809.87)


2019-11-14 13:55:04,220 - webcrawer service - INFO - 运行成功: ningxiazhaobiaowang_3_30_0, 一共：2条
2019-11-14 13:56:19,301 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-14 13:56:19,301 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 140, in RunMain
    html_str = model.parse_url("",url_type=parame["startPage"]["type"],url_params=parame["startPage"])
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 181, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div[1]/div[1]/div/input"}
  (Session info: chrome=76.0.3809.87)


2019-11-14 13:57:36,882 - webcrawer service - ERROR - 运行失败: ningxiazhaobiaowang_3_30_1
2019-11-14 13:57:36,898 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 140, in RunMain
    html_str = model.parse_url("",url_type=parame["startPage"]["type"],url_params=parame["startPage"])
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 181, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div[1]/div[1]/div/input"}
  (Session info: chrome=76.0.3809.87)


2019-11-14 14:00:28,282 - webcrawer service - INFO - 运行成功: ningxiazhaobiaowang_3_30_1, 一共：6条
2019-11-15 13:34:33,074 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_0, 一共：8条
2019-11-15 13:35:13,113 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_1, 一共：1条
2019-11-15 13:35:24,468 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_0, 一共：0条
2019-11-15 13:35:34,176 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_1, 一共：0条
2019-11-15 13:35:43,991 - webcrawer service - INFO - 运行成功: taipingyangbaoxian_3_3_0, 一共：0条
2019-11-15 13:39:06,158 - webcrawer service - INFO - 运行成功: tianjinshizhengfucaigoupingtai_3_4, 一共：15条
2019-11-15 13:39:20,358 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_0, 一共：0条
2019-11-15 13:39:39,606 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_1, 一共：0条
2019-11-15 13:40:44,589 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_0, 一共：1条
2019-11-15 13:41:53,884 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_1, 一共：1条
2019-11-15 13:45:45,613 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_0, 一共：14条
2019-11-15 13:50:36,223 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_1, 一共：12条
2019-11-15 13:52:03,823 - webcrawer service - INFO - 运行成功: shanghaigonggongziyuanjiaoyiwang_3_14, 一共：3条
2019-11-15 13:52:26,016 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_0, 一共：0条
2019-11-15 13:52:41,700 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_1, 一共：0条
2019-11-15 13:54:06,761 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_0, 一共：7条
2019-11-15 13:55:29,561 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_1, 一共：9条
2019-11-15 13:56:07,158 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_0, 一共：0条
2019-11-15 13:56:38,476 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_1, 一共：0条
2019-11-15 13:57:40,339 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_0, 一共：2条
2019-11-15 13:58:42,843 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_1, 一共：1条
2019-11-15 13:59:07,850 - webcrawer service - INFO - 运行成功: hainanshenggonggongziyuanjiaoyiwang_3_20, 一共：0条
2019-11-15 13:59:53,644 - webcrawer service - INFO - 运行成功: anzhaocai_3_23, 一共：0条
2019-11-15 14:00:16,224 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_0, 一共：0条
2019-11-15 14:00:39,626 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_1, 一共：0条
2019-11-15 14:01:03,286 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-15 14:01:33,852 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-15 14:01:48,447 - webcrawer service - INFO - 运行成功: chongqingguojitouzizixunjituanyouxiangongsi_3_27, 一共：0条
2019-11-15 14:02:06,914 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_0, 一共：0条
2019-11-15 14:02:25,141 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_1, 一共：0条
2019-11-15 14:03:01,305 - webcrawer service - ERROR - 运行失败: chengdushigonggongziyuanjiaoyizhongxin_3_29
2019-11-15 14:03:01,478 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 106, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 57, in getUrlList
    html_str = model.parse_url("",url_type=original_url,url_params=tmp_parame)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 181, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a href="javascript:__doPostBack('ctl00$ContentPlaceHolder1$Pager','...')">4</a> is not clickable at point (522, 598). Other element would receive the click: <div id="UpdatePanel1">...</div>
  (Session info: chrome=76.0.3809.87)


2019-11-15 14:04:17,280 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_0, 一共：10条
2019-11-15 14:05:41,136 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_1, 一共：16条
2019-11-15 14:06:26,075 - webcrawer service - INFO - 运行成功: bingtuanzhengfucaigouwang_3_32, 一共：0条
2019-11-15 14:09:38,483 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_0, 一共：11条
2019-11-15 14:10:03,851 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_1, 一共：0条
2019-11-15 14:26:03,387 - webcrawer service - INFO - 运行成功: hebeizhaobiaocaigouwang_3_9, 一共：85条
2019-11-15 14:34:40,588 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_0, 一共：34条
2019-11-15 14:42:06,137 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_1, 一共：37条
2019-11-15 14:54:23,872 - webcrawer service - INFO - 运行成功: liaoningshengcaigouzhaobiaowang_3_12_0, 一共：41条
2019-11-15 15:31:47,410 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_0, 一共：8条
2019-11-15 15:32:25,221 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_1, 一共：1条
2019-11-15 15:32:36,859 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_0, 一共：0条
2019-11-15 15:32:49,333 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_1, 一共：0条
2019-11-15 15:33:04,529 - webcrawer service - INFO - 运行成功: taipingyangbaoxian_3_3_0, 一共：0条
2019-11-15 15:36:47,684 - webcrawer service - INFO - 运行成功: tianjinshizhengfucaigoupingtai_3_4, 一共：15条
2019-11-15 15:37:01,808 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_0, 一共：0条
2019-11-15 15:37:17,573 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_1, 一共：0条
2019-11-15 15:38:24,176 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_0, 一共：1条
2019-11-15 15:39:27,305 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_1, 一共：1条
2019-11-15 15:44:23,850 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_0, 一共：14条
2019-11-15 15:50:33,798 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_1, 一共：12条
2019-11-15 15:55:16,809 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_0, 一共：11条
2019-11-15 15:55:44,458 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_1, 一共：0条
2019-11-15 16:11:24,010 - webcrawer service - INFO - 运行成功: hebeizhaobiaocaigouwang_3_9, 一共：68条
2019-11-15 16:15:43,223 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_0, 一共：20条
2019-11-15 16:16:37,736 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_1, 一共：0条
2019-11-15 16:25:35,160 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_0, 一共：35条
2019-11-15 16:33:22,113 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_1, 一共：37条
2019-11-15 16:52:07,832 - webcrawer service - INFO - 运行成功: liaoningshengcaigouzhaobiaowang_3_12_0, 一共：41条
2019-11-15 17:04:31,622 - webcrawer service - INFO - 运行成功: liaoningshengcaigouzhaobiaowang_3_12_1, 一共：39条
2019-11-15 17:05:06,888 - webcrawer service - INFO - 运行成功: dalianshizhaobiaowang_3_13, 一共：0条
2019-11-15 17:05:18,605 - webcrawer service - INFO - 运行成功: shanghaigonggongziyuanjiaoyiwang_3_14, 一共：0条
2019-11-15 17:05:35,681 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_0, 一共：0条
2019-11-15 17:05:50,462 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_1, 一共：0条
2019-11-15 17:07:16,161 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_0, 一共：7条
2019-11-15 17:08:37,619 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_1, 一共：9条
2019-11-15 17:32:20,573 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_0, 一共：110条
2019-11-15 17:46:24,420 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_1, 一共：93条
2019-11-15 17:47:09,833 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_0, 一共：0条
2019-11-15 17:47:43,893 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_1, 一共：0条
2019-11-15 17:49:01,485 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_0, 一共：2条
2019-11-15 17:50:02,843 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_1, 一共：1条
2019-11-15 17:50:20,552 - webcrawer service - INFO - 运行成功: hainanshenggonggongziyuanjiaoyiwang_3_20, 一共：0条
2019-11-15 17:55:30,753 - webcrawer service - INFO - 运行成功: shenzhenqinglima_3_21_0, 一共：26条
2019-11-15 17:59:44,483 - webcrawer service - INFO - 运行成功: shenzhenqinglima_3_21_1, 一共：23条
2019-11-15 18:00:19,357 - webcrawer service - INFO - 运行成功: anzhaocai_3_23, 一共：0条
2019-11-15 18:00:34,082 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_0, 一共：0条
2019-11-15 18:00:48,726 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_1, 一共：0条
2019-11-15 18:01:05,343 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-15 18:01:20,482 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-15 18:01:45,976 - webcrawer service - INFO - 运行成功: chongqingguojitouzizixunjituanyouxiangongsi_3_27, 一共：0条
2019-11-15 18:02:00,394 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_0, 一共：0条
2019-11-15 18:02:13,972 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_1, 一共：0条
2019-11-15 18:03:04,488 - webcrawer service - ERROR - 运行失败: chengdushigonggongziyuanjiaoyizhongxin_3_29
2019-11-15 18:03:04,633 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 106, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 57, in getUrlList
    html_str = model.parse_url("",url_type=original_url,url_params=tmp_parame)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 212, in parse_url
    return html_str
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="Pager"]/a[text()=11]"}
  (Session info: chrome=76.0.3809.87)


2019-11-15 18:05:21,745 - webcrawer service - INFO - 运行成功: ningxiazhaobiaowang_3_30_0, 一共：1条
2019-11-15 18:08:25,121 - webcrawer service - INFO - 运行成功: ningxiazhaobiaowang_3_30_1, 一共：2条
2019-11-15 18:09:39,074 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_0, 一共：11条
2019-11-15 18:11:01,665 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_1, 一共：16条
2019-11-15 18:11:50,764 - webcrawer service - INFO - 运行成功: bingtuanzhengfucaigouwang_3_32, 一共：0条
2019-11-18 09:58:42,892 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_0, 一共：5条
2019-11-18 09:59:23,221 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_1, 一共：0条
2019-11-18 10:01:51,426 - webcrawer service - INFO - 运行成功: tianjinzhaobiaowang2_4_0, 一共：2条
2019-11-18 10:04:20,264 - webcrawer service - INFO - 运行成功: shandongzhaobiaocaigouwang2_6_0, 一共：6条
2019-11-18 10:09:01,578 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_0, 一共：5条
2019-11-18 10:09:48,796 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_1, 一共：0条
2019-11-18 10:11:27,673 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_0, 一共：0条
2019-11-18 10:13:10,725 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_1, 一共：0条
2019-11-18 11:16:04,892 - webcrawer service - ERROR - 运行失败: yunnanshengzhengfucaigouwang_3_26_0
2019-11-18 11:16:05,024 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 126, in RunMain
    html_str = model.parse_url("",url_type=url_info["type"],url_params=url_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 214, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 系统异常请联系管理员！
Message: unexpected alert open: {Alert text : 系统异常请联系管理员！}
  (Session info: chrome=76.0.3809.87)


2019-11-18 11:16:23,104 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-18 11:25:29,757 - webcrawer service - ERROR - 运行失败: yunnanshengzhengfucaigouwang_3_26_0
2019-11-18 11:25:30,010 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 126, in RunMain
    html_str = model.parse_url("",url_type=url_info["type"],url_params=url_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 214, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div[2]/div[2]/div[1]/div/a"}
  (Session info: chrome=76.0.3809.87)


2019-11-18 11:28:55,523 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-18 11:29:16,394 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-18 11:30:39,853 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-18 11:33:14,518 - webcrawer service - ERROR - 运行失败: yunnanshengzhengfucaigouwang_3_26_0
2019-11-18 11:33:15,260 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 126, in RunMain
    html_str = model.parse_url("",url_type=url_info["type"],url_params=url_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 214, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 系统异常请联系管理员！
Message: unexpected alert open: {Alert text : 系统异常请联系管理员！}
  (Session info: chrome=76.0.3809.87)


2019-11-18 11:34:02,517 - webcrawer service - ERROR - 运行失败: yunnanshengzhengfucaigouwang_3_26_1
2019-11-18 11:34:03,099 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 126, in RunMain
    html_str = model.parse_url("",url_type=url_info["type"],url_params=url_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 214, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="query2"]/font/b"}
  (Session info: chrome=76.0.3809.87)


2019-11-18 11:34:42,293 - webcrawer service - ERROR - 运行失败: yunnanshengzhengfucaigouwang_3_26_0
2019-11-18 11:34:42,295 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 126, in RunMain
    html_str = model.parse_url("",url_type=url_info["type"],url_params=url_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 214, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 系统异常请联系管理员！
Message: unexpected alert open: {Alert text : 系统异常请联系管理员！}
  (Session info: chrome=76.0.3809.87)


2019-11-18 11:34:54,486 - webcrawer service - ERROR - 运行失败: yunnanshengzhengfucaigouwang_3_26_1
2019-11-18 11:34:54,489 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 126, in RunMain
    html_str = model.parse_url("",url_type=url_info["type"],url_params=url_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 214, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 系统异常请联系管理员！
Message: unexpected alert open: {Alert text : 系统异常请联系管理员！}
  (Session info: chrome=76.0.3809.87)


2019-11-18 11:44:47,371 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-18 11:44:59,549 - webcrawer service - ERROR - 运行失败: yunnanshengzhengfucaigouwang_3_26_1
2019-11-18 11:44:59,553 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 126, in RunMain
    html_str = model.parse_url("",url_type=url_info["type"],url_params=url_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 214, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="query2"]/font/b"}
  (Session info: chrome=76.0.3809.87)


2019-11-19 09:41:58,413 - webcrawer service - ERROR - 运行失败: fujianshengzhengfucaigouguanwang2_18_0
2019-11-19 09:41:58,497 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 97, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 180, in log_in_web
    self.cookie_info = self.driver.get_cookies()                 # 列表中包含多个字典
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 841, in get_cookies
    return self.execute(Command.GET_ALL_COOKIES)['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 请输入验证码！
Message: unexpected alert open: {Alert text : 请输入验证码！}
  (Session info: chrome=76.0.3809.87)


2019-11-20 11:19:03,229 - webcrawer service - INFO - 运行成功: jincai_1, 一共：4条
2019-11-20 11:22:42,922 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_0, 一共：1条
2019-11-20 11:23:13,404 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_1, 一共：2条
2019-11-20 11:23:25,985 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_0, 一共：0条
2019-11-20 11:23:37,426 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_1, 一共：0条
2019-11-20 11:23:50,390 - webcrawer service - INFO - 运行成功: taipingyangbaoxian_3_3_0, 一共：0条
2019-11-20 11:24:11,801 - webcrawer service - INFO - 运行成功: tianjinshizhengfucaigoupingtai_3_4, 一共：0条
2019-11-20 11:24:24,310 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_0, 一共：0条
2019-11-20 11:24:38,998 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_1, 一共：0条
2019-11-20 11:25:01,644 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_0, 一共：0条
2019-11-20 11:25:26,326 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_1, 一共：0条
2019-11-20 11:25:37,092 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_0, 一共：0条
2019-11-20 11:26:41,607 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_1, 一共：3条
2019-11-20 11:27:20,342 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_0, 一共：0条
2019-11-20 11:27:45,139 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_1, 一共：0条
2019-11-20 11:34:49,578 - webcrawer service - INFO - 运行成功: hebeizhaobiaocaigouwang_3_9, 一共：26条
2019-11-20 11:37:17,277 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_0, 一共：4条
2019-11-20 11:39:37,591 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_1, 一共：2条
2019-11-20 11:41:40,659 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_0, 一共：8条
2019-11-20 11:44:12,675 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_1, 一共：19条
2019-11-20 11:46:59,907 - webcrawer service - INFO - 运行成功: liaoningshengcaigouzhaobiaowang_3_12_0, 一共：10条
2019-11-20 11:49:00,570 - webcrawer service - INFO - 运行成功: liaoningshengcaigouzhaobiaowang_3_12_1, 一共：2条
2019-11-20 11:51:26,217 - webcrawer service - INFO - 运行成功: dalianshizhaobiaowang_3_13, 一共：1条
2019-11-20 11:51:42,981 - webcrawer service - INFO - 运行成功: shanghaigonggongziyuanjiaoyiwang_3_14, 一共：0条
2019-11-20 11:52:02,790 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_0, 一共：0条
2019-11-20 11:52:28,536 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_1, 一共：0条
2019-11-20 11:53:05,756 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_0, 一共：1条
2019-11-20 11:53:38,504 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_1, 一共：1条
2019-11-20 11:54:05,225 - webcrawer service - ERROR - 运行失败: guangdongzhaobiaowang_3_17_0
2019-11-20 11:54:05,406 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 97, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 183, in log_in_web
    self.cookie_info = self.driver.get_cookies()                 # 列表中包含多个字典
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 841, in get_cookies
    return self.execute(Command.GET_ALL_COOKIES)['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 验证码错误，请重新输入验证码。
Message: unexpected alert open: {Alert text : 验证码错误，请重新输入验证码。}
  (Session info: headless chrome=76.0.3809.87)


2019-11-20 11:57:49,833 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_1, 一共：17条
2019-11-20 11:58:24,113 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_0, 一共：0条
2019-11-20 11:59:06,793 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_1, 一共：0条
2019-11-20 11:59:43,625 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_0, 一共：2条
2019-11-20 11:59:59,128 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_1, 一共：0条
2019-11-20 12:00:13,130 - webcrawer service - INFO - 运行成功: hainanshenggonggongziyuanjiaoyiwang_3_20, 一共：0条
2019-11-20 12:02:09,713 - webcrawer service - INFO - 运行成功: shenzhenqinglima_3_21_0, 一共：3条
2019-11-20 12:02:54,982 - webcrawer service - INFO - 运行成功: shenzhenqinglima_3_21_1, 一共：0条
2019-11-20 12:03:32,128 - webcrawer service - INFO - 运行成功: anzhaocai_3_23, 一共：0条
2019-11-20 12:03:43,095 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_0, 一共：0条
2019-11-20 12:03:54,677 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_1, 一共：0条
2019-11-20 12:04:09,284 - webcrawer service - ERROR - 运行失败: yunnanshengzhengfucaigouwang_3_26_0
2019-11-20 12:04:09,346 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 126, in RunMain
    html_str = model.parse_url("",url_type=url_info["type"],url_params=url_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 229, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 系统异常请联系管理员！
Message: unexpected alert open: {Alert text : 系统异常请联系管理员！}
  (Session info: headless chrome=76.0.3809.87)


2019-11-20 12:04:38,834 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-20 12:04:49,583 - webcrawer service - INFO - 运行成功: chongqingguojitouzizixunjituanyouxiangongsi_3_27, 一共：0条
2019-11-20 12:24:54,958 - webcrawer service - ERROR - 运行失败: lasagonggongziyuanjiaoyiwang_3_28_0
2019-11-20 12:24:54,958 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 106, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 26, in getUrlList
    ori_number = model.number_page(parame["number_xpath"], html_str)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 580, in number_page
    number = html_element.xpath(number_xpath)
AttributeError: 'NoneType' object has no attribute 'xpath'

2019-11-20 12:45:00,331 - webcrawer service - ERROR - 运行失败: lasagonggongziyuanjiaoyiwang_3_28_1
2019-11-20 12:45:00,332 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 106, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 26, in getUrlList
    ori_number = model.number_page(parame["number_xpath"], html_str)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 580, in number_page
    number = html_element.xpath(number_xpath)
AttributeError: 'NoneType' object has no attribute 'xpath'

2019-11-20 12:45:26,147 - webcrawer service - INFO - 运行成功: chengdushigonggongziyuanjiaoyizhongxin_3_29, 一共：0条
2019-11-20 12:46:10,579 - webcrawer service - INFO - 运行成功: ningxiazhaobiaowang_3_30_0, 一共：0条
2019-11-20 12:47:39,829 - webcrawer service - INFO - 运行成功: ningxiazhaobiaowang_3_30_1, 一共：1条
2019-11-20 12:48:48,068 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_0, 一共：5条
2019-11-20 12:48:59,326 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_1, 一共：0条
2019-11-20 12:49:17,214 - webcrawer service - INFO - 运行成功: bingtuanzhengfucaigouwang_3_32, 一共：0条
2019-11-20 14:29:52,802 - webcrawer service - ERROR - 运行失败: lasagonggongziyuanjiaoyiwang_3_28_0
2019-11-20 14:29:52,805 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 106, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 26, in getUrlList
    ori_number = model.number_page(parame["number_xpath"], html_str)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 580, in number_page
    number = html_element.xpath(number_xpath)
AttributeError: 'NoneType' object has no attribute 'xpath'

2019-11-20 14:49:58,195 - webcrawer service - ERROR - 运行失败: lasagonggongziyuanjiaoyiwang_3_28_1
2019-11-20 14:49:58,196 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 106, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 26, in getUrlList
    ori_number = model.number_page(parame["number_xpath"], html_str)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 580, in number_page
    number = html_element.xpath(number_xpath)
AttributeError: 'NoneType' object has no attribute 'xpath'

2019-11-20 15:02:27,558 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_0, 一共：37条
2019-11-20 15:06:59,150 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_0, 一共：0条
2019-11-20 15:07:15,758 - webcrawer service - INFO - 运行成功: lasagonggongziyuanjiaoyiwang_3_28_1, 一共：0条
2019-11-20 15:09:15,993 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_0, 一共：1条
2019-11-20 15:09:46,820 - webcrawer service - INFO - 运行成功: zhongzhaoguojizhaobiaoyouxiangongsi_3_1_1, 一共：2条
2019-11-20 15:09:58,777 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_0, 一共：0条
2019-11-20 15:10:11,122 - webcrawer service - INFO - 运行成功: zhonggangzhaobiaoyouxianzerengongsi_3_2_1, 一共：0条
2019-11-20 15:10:25,504 - webcrawer service - INFO - 运行成功: taipingyangbaoxian_3_3_0, 一共：0条
2019-11-20 15:10:47,031 - webcrawer service - INFO - 运行成功: tianjinshizhengfucaigoupingtai_3_4, 一共：0条
2019-11-20 15:11:02,269 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_0, 一共：0条
2019-11-20 15:11:14,410 - webcrawer service - INFO - 运行成功: neimengguzizhiqugonggongziyuanjiaoyiwang_3_5_1, 一共：0条
2019-11-20 15:11:29,956 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_0, 一共：0条
2019-11-20 15:11:52,498 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_3_6_1, 一共：0条
2019-11-20 15:13:13,058 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_0, 一共：5条
2019-11-20 15:15:16,348 - webcrawer service - INFO - 运行成功: shandongshengzhengfucaigouxinxigongkaipingtai_shixian_3_6_1, 一共：6条
2019-11-20 15:16:18,619 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_0, 一共：0条
2019-11-20 15:16:52,140 - webcrawer service - ERROR - 运行失败: huazhongzhaobiaowang_3_8_1
2019-11-20 15:16:52,207 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 97, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 183, in log_in_web
    self.cookie_info = self.driver.get_cookies()                 # 列表中包含多个字典
AttributeError: 'bool' object has no attribute 'get_cookies'

2019-11-20 15:17:58,961 - webcrawer service - INFO - 运行成功: hebeizhaobiaocaigouwang_3_9, 一共：0条
2019-11-20 15:20:26,634 - webcrawer service - INFO - 运行成功: heilongjiangzhaobiaowang_3_10_0, 一共：8条
2019-11-20 15:20:52,529 - webcrawer service - ERROR - 运行失败: heilongjiangzhaobiaowang_3_10_1
2019-11-20 15:20:52,549 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 148, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 97, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 183, in log_in_web
    self.cookie_info = self.driver.get_cookies()                 # 列表中包含多个字典
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 841, in get_cookies
    return self.execute(Command.GET_ALL_COOKIES)['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 验证码错误，请重新输入验证码。
Message: unexpected alert open: {Alert text : 验证码错误，请重新输入验证码。}
  (Session info: headless chrome=76.0.3809.87)


2019-11-20 15:24:13,409 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_0, 一共：15条
2019-11-20 15:27:23,715 - webcrawer service - INFO - 运行成功: jilinshengcaigouzhaobiaowang_3_11_1, 一共：25条
2019-11-20 15:32:53,472 - webcrawer service - INFO - 运行成功: liaoningshengcaigouzhaobiaowang_3_12_0, 一共：22条
2019-11-20 15:36:45,471 - webcrawer service - INFO - 运行成功: liaoningshengcaigouzhaobiaowang_3_12_1, 一共：8条
2019-11-20 15:37:20,525 - webcrawer service - INFO - 运行成功: dalianshizhaobiaowang_3_13, 一共：0条
2019-11-20 15:37:32,832 - webcrawer service - INFO - 运行成功: shanghaigonggongziyuanjiaoyiwang_3_14, 一共：0条
2019-11-20 15:38:21,074 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_0, 一共：0条
2019-11-20 15:38:42,530 - webcrawer service - INFO - 运行成功: zhejiangshenggonggongziyuanjiaoyiwang_3_15_1, 一共：0条
2019-11-20 15:39:33,332 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_0, 一共：4条
2019-11-20 15:40:20,363 - webcrawer service - INFO - 运行成功: jiangsuzhengfucaigouwang_3_16_1, 一共：5条
2019-11-20 15:47:03,332 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_0, 一共：47条
2019-11-20 15:52:20,168 - webcrawer service - INFO - 运行成功: guangdongzhaobiaowang_3_17_1, 一共：40条
2019-11-20 15:53:14,278 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_0, 一共：0条
2019-11-20 15:53:55,663 - webcrawer service - INFO - 运行成功: xiamenshigongongziyuanjiaoyiwang_3_18_1, 一共：0条
2019-11-20 15:54:32,370 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_0, 一共：2条
2019-11-20 15:54:50,564 - webcrawer service - INFO - 运行成功: guangxizhaobiaotoubiaogonggongfuwupingtai_3_19_1, 一共：0条
2019-11-20 15:55:18,601 - webcrawer service - INFO - 运行成功: hainanshenggonggongziyuanjiaoyiwang_3_20, 一共：0条
2019-11-20 15:57:12,764 - webcrawer service - INFO - 运行成功: shenzhenqinglima_3_21_0, 一共：3条
2019-11-20 16:00:21,744 - webcrawer service - INFO - 运行成功: shenzhenqinglima_3_21_1, 一共：1条
2019-11-20 16:00:58,654 - webcrawer service - INFO - 运行成功: anzhaocai_3_23, 一共：0条
2019-11-20 16:01:10,063 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_0, 一共：0条
2019-11-20 16:01:20,893 - webcrawer service - INFO - 运行成功: jiangxiguozhengzhaobiaoyouxiangongsi_3_24_1, 一共：0条
2019-11-20 16:01:47,010 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-20 16:02:14,934 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-20 16:02:29,725 - webcrawer service - INFO - 运行成功: chongqingguojitouzizixunjituanyouxiangongsi_3_27, 一共：0条
2019-11-21 15:23:33,009 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-21 15:23:51,980 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-21 15:32:22,094 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-21 15:40:56,463 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-21 15:41:20,430 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-21 15:42:39,107 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-21 15:43:49,636 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-21 15:45:49,351 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_0, 一共：0条
2019-11-21 15:46:17,170 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：0条
2019-11-21 16:00:10,031 - webcrawer service - INFO - 运行成功: yunnanshengzhengfucaigouwang_3_26_1, 一共：3条
2019-11-28 00:00:05,509 - webcrawer service - INFO - current website is jincai_1
2019-11-28 00:01:56,508 - webcrawer service - INFO - 运行成功: jincai_1, 一共：30条
2019-11-28 00:01:56,508 - webcrawer service - INFO - current website is zhongguozhaobiaoyucaigouwang_3
2019-11-28 04:08:33,421 - webcrawer service - INFO - 运行成功: zhongguozhaobiaoyucaigouwang_3, 一共：4163条
2019-11-28 04:08:33,508 - webcrawer service - INFO - current website is zhongguozhengfucaigouwang_4
2019-11-28 04:51:00,489 - webcrawer service - INFO - 运行成功: zhongguozhengfucaigouwang_4, 一共：381条
2019-11-28 04:51:00,490 - webcrawer service - INFO - current website is zhongguoyidongcaigouyuzhaobiao_5_0
2019-11-28 04:51:44,988 - webcrawer service - INFO - 运行成功: zhongguoyidongcaigouyuzhaobiao_5_0, 一共：3条
2019-11-28 04:51:44,988 - webcrawer service - INFO - current website is guodianzhaobiaowang_7_0
2019-11-28 04:51:59,119 - webcrawer service - INFO - 运行成功: guodianzhaobiaowang_7_0, 一共：0条
2019-11-28 04:51:59,120 - webcrawer service - INFO - current website is beijingshizhengfu_8
2019-11-28 04:53:55,656 - webcrawer service - INFO - 运行成功: beijingshizhengfu_8, 一共：9条
2019-11-28 04:53:55,656 - webcrawer service - INFO - current website is zhonghuazhaobiao_9_0
2019-11-28 04:54:28,128 - webcrawer service - INFO - 运行成功: zhonghuazhaobiao_9_0, 一共：1条
2019-11-28 04:54:28,128 - webcrawer service - INFO - current website is renbao_10
2019-11-28 04:54:40,855 - webcrawer service - INFO - 运行成功: renbao_10, 一共：0条
2019-11-28 04:54:40,855 - webcrawer service - INFO - current website is guoshou_11
2019-11-28 04:54:52,076 - webcrawer service - INFO - 运行成功: guoshou_11, 一共：0条
2019-11-28 04:54:52,077 - webcrawer service - INFO - current website is anbang_12
2019-11-28 04:55:03,386 - webcrawer service - INFO - 运行成功: anbang_12, 一共：0条
2019-11-28 04:55:03,386 - webcrawer service - INFO - current website is taikang_13_0
2019-11-28 04:55:32,420 - webcrawer service - INFO - 运行成功: taikang_13_0, 一共：3条
2019-11-28 04:55:32,421 - webcrawer service - INFO - current website is changchengzichan_14
2019-11-28 04:55:56,163 - webcrawer service - INFO - 运行成功: changchengzichan_14, 一共：1条
2019-11-28 04:55:56,163 - webcrawer service - INFO - current website is xindazichan_15
2019-11-28 04:56:12,271 - webcrawer service - INFO - 运行成功: xindazichan_15, 一共：0条
2019-11-28 04:56:12,272 - webcrawer service - INFO - current website is yangguangbaoxian_16
2019-11-28 04:56:23,208 - webcrawer service - INFO - 运行成功: yangguangbaoxian_16, 一共：0条
2019-11-28 04:56:23,208 - webcrawer service - INFO - current website is chukouxinyongbaoxian_17
2019-11-28 04:56:34,561 - webcrawer service - INFO - 运行成功: chukouxinyongbaoxian_17, 一共：0条
2019-11-28 04:56:34,561 - webcrawer service - INFO - current website is huahai_18
2019-11-28 04:56:46,515 - webcrawer service - INFO - 运行成功: huahai_18, 一共：0条
2019-11-28 04:56:46,516 - webcrawer service - INFO - current website is zhongxinzhaobiao_19
2019-11-28 04:57:36,299 - webcrawer service - INFO - 运行成功: zhongxinzhaobiao_19, 一共：9条
2019-11-28 04:57:36,300 - webcrawer service - INFO - current website is zhongzhenxinxi_20
2019-11-28 04:57:47,949 - webcrawer service - INFO - 运行成功: zhongzhenxinxi_20, 一共：0条
2019-11-28 04:57:47,949 - webcrawer service - INFO - current website is guojiadianwang_21
2019-11-28 04:58:17,517 - webcrawer service - INFO - 运行成功: guojiadianwang_21, 一共：1条
2019-11-28 04:58:17,517 - webcrawer service - INFO - current website is guohang_22
2019-11-28 04:58:45,933 - webcrawer service - INFO - 运行成功: guohang_22, 一共：1条
2019-11-28 04:58:45,934 - webcrawer service - INFO - current website is youzheng_23_0
2019-11-28 04:58:57,482 - webcrawer service - INFO - 运行成功: youzheng_23_0, 一共：0条
2019-11-28 04:58:57,482 - webcrawer service - INFO - current website is tieta_24
2019-11-28 04:59:06,215 - webcrawer service - INFO - 运行成功: tieta_24, 一共：0条
2019-11-28 04:59:06,216 - webcrawer service - INFO - current website is zhongguodianzijinchukou_26
2019-11-28 04:59:18,029 - webcrawer service - INFO - 运行成功: zhongguodianzijinchukou_26, 一共：0条
2019-11-28 04:59:18,029 - webcrawer service - INFO - current website is zhongguodianwangzhucexinxi_27
2019-11-28 04:59:30,808 - webcrawer service - INFO - 运行成功: zhongguodianwangzhucexinxi_27, 一共：0条
2019-11-28 04:59:30,808 - webcrawer service - INFO - current website is chengEzhaobiao_28
2019-11-28 05:00:32,704 - webcrawer service - INFO - 运行成功: chengEzhaobiao_28, 一共：7条
2019-11-28 05:00:32,704 - webcrawer service - INFO - current website is neimengguzhaobiao_29_0
2019-11-28 05:00:44,894 - webcrawer service - INFO - 运行成功: neimengguzhaobiao_29_0, 一共：0条
2019-11-28 05:00:44,895 - webcrawer service - INFO - current website is zhonghuashangwupingtai_1_1_0
2019-11-28 05:01:21,848 - webcrawer service - INFO - 运行成功: zhonghuashangwupingtai_1_1_0, 一共：1条
2019-11-28 05:01:21,849 - webcrawer service - INFO - current website is zhonghuashangwupingtai_1_1_1
2019-11-28 05:02:00,197 - webcrawer service - INFO - 运行成功: zhonghuashangwupingtai_1_1_1, 一共：3条
2019-11-28 05:02:00,197 - webcrawer service - INFO - current website is zhongguorenminbaoxiancaigou_1_3_0
2019-11-28 05:02:12,470 - webcrawer service - INFO - 运行成功: zhongguorenminbaoxiancaigou_1_3_0, 一共：0条
2019-11-28 05:02:12,471 - webcrawer service - INFO - current website is qinglima_1_4_0
2019-11-28 05:07:19,262 - webcrawer service - INFO - 运行成功: qinglima_1_4_0, 一共：42条
2019-11-28 05:07:19,263 - webcrawer service - INFO - current website is qinglima_1_4_1
2019-11-28 05:07:54,572 - webcrawer service - INFO - 运行成功: qinglima_1_4_1, 一共：0条
2019-11-28 05:07:54,573 - webcrawer service - INFO - current website is shandongcaigouyuzhaobiao_1_6_0
2019-11-28 05:08:50,072 - webcrawer service - INFO - 运行成功: shandongcaigouyuzhaobiao_1_6_0, 一共：4条
2019-11-28 05:08:50,072 - webcrawer service - INFO - current website is shandongcaigouyuzhaobiao_1_6_1
2019-11-28 05:09:45,094 - webcrawer service - INFO - 运行成功: shandongcaigouyuzhaobiao_1_6_1, 一共：6条
2019-11-28 05:09:45,094 - webcrawer service - INFO - current website is shanxishenzhaobiaogonggongfuwupingtai_1_7_0
2019-11-28 05:11:37,623 - webcrawer service - INFO - 运行成功: shanxishenzhaobiaogonggongfuwupingtai_1_7_0, 一共：7条
2019-11-28 05:11:37,623 - webcrawer service - INFO - current website is shanxishenzhaobiaogonggongfuwupingtai_1_7_1
2019-11-28 05:12:41,491 - webcrawer service - INFO - 运行成功: shanxishenzhaobiaogonggongfuwupingtai_1_7_1, 一共：3条
2019-11-28 05:12:41,492 - webcrawer service - INFO - current website is zhongyuanzhaocai_1_8_0
2019-11-28 05:13:06,350 - webcrawer service - INFO - 运行成功: zhongyuanzhaocai_1_8_0, 一共：0条
2019-11-28 05:13:06,350 - webcrawer service - INFO - current website is zhongyuanzhaocai_1_8_1
2019-11-28 05:13:31,059 - webcrawer service - INFO - 运行成功: zhongyuanzhaocai_1_8_1, 一共：0条
2019-11-28 05:13:31,059 - webcrawer service - INFO - current website is heibeishenzhaobiaotoubiao_1_9_0
2019-11-28 05:15:01,676 - webcrawer service - INFO - 运行成功: heibeishenzhaobiaotoubiao_1_9_0, 一共：15条
2019-11-28 05:15:01,677 - webcrawer service - INFO - current website is heibeishengzhaobiaotoubiao_1_9_1
2019-11-28 05:15:41,759 - webcrawer service - INFO - 运行成功: heibeishengzhaobiaotoubiao_1_9_1, 一共：3条
2019-11-28 05:15:41,760 - webcrawer service - INFO - current website is heilongjiangcaigou_1_10_0
2019-11-28 05:16:34,410 - webcrawer service - INFO - 运行成功: heilongjiangcaigou_1_10_0, 一共：3条
2019-11-28 05:16:34,411 - webcrawer service - INFO - current website is jilinzhaobiao_1_11_0
2019-11-28 05:17:16,219 - webcrawer service - INFO - 运行成功: jilinzhaobiao_1_11_0, 一共：0条
2019-11-28 05:17:16,220 - webcrawer service - INFO - current website is jilinzhaobiao_1_11_1
2019-11-28 05:17:53,748 - webcrawer service - INFO - 运行成功: jilinzhaobiao_1_11_1, 一共：0条
2019-11-28 05:17:53,749 - webcrawer service - INFO - current website is liaoningzhaobiao_1_12_0
2019-11-28 05:28:05,587 - webcrawer service - ERROR - 运行失败: liaoningzhaobiao_1_12_0
2019-11-28 05:28:05,641 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 151, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test_login.py", line 113, in RunMain
    driver = model.log_in_web(*login_infos)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 203, in log_in_web
    self.cookie_info = self.driver.get_cookies()                 # 列表中包含多个字典
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 841, in get_cookies
    return self.execute(Command.GET_ALL_COOKIES)['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=76.0.3809.87)


2019-11-28 05:28:05,641 - webcrawer service - INFO - current website is liaoningzhaobiao_1_12_1
2019-11-28 05:33:36,489 - webcrawer service - INFO - 运行成功: liaoningzhaobiao_1_12_1, 一共：19条
2019-11-28 05:33:36,489 - webcrawer service - INFO - current website is dalianzhaobiao_1_13_0
2019-11-28 05:36:18,476 - webcrawer service - INFO - 运行成功: dalianzhaobiao_1_13_0, 一共：7条
2019-11-28 05:36:18,477 - webcrawer service - INFO - current website is dalianzhaobiao_1_13_1
2019-11-28 05:39:21,171 - webcrawer service - INFO - 运行成功: dalianzhaobiao_1_13_1, 一共：17条
2019-11-28 05:39:21,172 - webcrawer service - INFO - current website is shanghaizhaobiao_1_14_0
2019-11-28 05:39:59,121 - webcrawer service - INFO - 运行成功: shanghaizhaobiao_1_14_0, 一共：0条
2019-11-28 05:39:59,121 - webcrawer service - INFO - current website is shanghaizhaobiao_1_14_1
2019-11-28 05:40:36,498 - webcrawer service - INFO - 运行成功: shanghaizhaobiao_1_14_1, 一共：0条
2019-11-28 05:40:36,498 - webcrawer service - INFO - current website is zhejiangzhaobiao_1_15_0
2019-11-28 05:41:14,379 - webcrawer service - INFO - 运行成功: zhejiangzhaobiao_1_15_0, 一共：0条
2019-11-28 05:41:14,379 - webcrawer service - INFO - current website is zhejiangzhaobiao_1_15_1
2019-11-28 05:41:52,123 - webcrawer service - INFO - 运行成功: zhejiangzhaobiao_1_15_1, 一共：0条
2019-11-28 05:41:52,123 - webcrawer service - INFO - current website is jiangsuzhaobiao_1_16_0
2019-11-28 05:44:46,207 - webcrawer service - INFO - 运行成功: jiangsuzhaobiao_1_16_0, 一共：0条
2019-11-28 05:44:46,208 - webcrawer service - INFO - current website is jiangsuzhaobiao_1_16_1
2019-11-28 05:45:23,784 - webcrawer service - INFO - 运行成功: jiangsuzhaobiao_1_16_1, 一共：0条
2019-11-28 05:45:23,785 - webcrawer service - INFO - current website is guangdongshenzhengfucaigou_1_17_0
2019-11-28 05:47:30,830 - webcrawer service - INFO - 运行成功: guangdongshenzhengfucaigou_1_17_0, 一共：10条
2019-11-28 05:47:30,830 - webcrawer service - INFO - current website is guangdongshenzhengfucaigou_1_17_1
2019-11-28 05:49:52,327 - webcrawer service - INFO - 运行成功: guangdongshenzhengfucaigou_1_17_1, 一共：15条
2019-11-28 05:49:52,328 - webcrawer service - INFO - current website is neimengguzizhiquzhengfucaigou
2019-11-28 05:51:18,663 - webcrawer service - INFO - 运行成功: neimengguzizhiquzhengfucaigou, 一共：8条
2019-11-28 05:51:18,663 - webcrawer service - INFO - current website is neimengguzizhiquzhengfucaigou_1
2019-11-28 05:51:34,506 - webcrawer service - ERROR - 运行失败: neimengguzizhiquzhengfucaigou_1
2019-11-28 05:51:34,557 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 151, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 145, in RunMain
    html_str = model.parse_url("",url_type=url_info["type"],url_params=url_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 259, in parse_url
    params= url_param["params"]
KeyError: 'params'

2019-11-28 05:51:34,557 - webcrawer service - INFO - current website is fujianshengonggongziyuanjiaoyi_1_18_0
2019-11-28 05:51:53,269 - webcrawer service - INFO - 运行成功: fujianshengonggongziyuanjiaoyi_1_18_0, 一共：0条
2019-11-28 05:51:53,269 - webcrawer service - INFO - current website is guangxizhaobiao_1_19_0
2019-11-28 05:52:21,363 - webcrawer service - INFO - 运行成功: guangxizhaobiao_1_19_0, 一共：1条
2019-11-28 05:52:21,363 - webcrawer service - INFO - current website is guangxizhaobiao_1_19_1
2019-11-28 05:52:37,172 - webcrawer service - INFO - 运行成功: guangxizhaobiao_1_19_1, 一共：0条
2019-11-28 05:52:37,173 - webcrawer service - INFO - current website is hainanzhaobiao_1_20_0
2019-11-28 05:54:38,938 - webcrawer service - INFO - 运行成功: hainanzhaobiao_1_20_0, 一共：5条
2019-11-28 05:54:38,938 - webcrawer service - INFO - current website is hainanzhaobiao_1_20_1
2019-11-28 05:55:53,931 - webcrawer service - INFO - 运行成功: hainanzhaobiao_1_20_1, 一共：2条
2019-11-28 05:55:53,932 - webcrawer service - INFO - current website is shenzhenshiguojizhaobiao_1_21_0
2019-11-28 05:56:10,135 - webcrawer service - INFO - 运行成功: shenzhenshiguojizhaobiao_1_21_0, 一共：0条
2019-11-28 05:56:10,136 - webcrawer service - INFO - current website is shenzhenshiguojizhaobiao_1_21_1
2019-11-28 05:56:41,325 - webcrawer service - INFO - 运行成功: shenzhenshiguojizhaobiao_1_21_1, 一共：2条
2019-11-28 05:56:41,326 - webcrawer service - INFO - current website is hunanxiangzigongchengzixu_1_22_0
2019-11-28 05:56:59,955 - webcrawer service - INFO - 运行成功: hunanxiangzigongchengzixu_1_22_0, 一共：0条
2019-11-28 05:56:59,955 - webcrawer service - INFO - current website is hunanxiangzigongchengzixu_1_22_1
2019-11-28 05:57:18,447 - webcrawer service - INFO - 运行成功: hunanxiangzigongchengzixu_1_22_1, 一共：0条
2019-11-28 05:57:18,448 - webcrawer service - INFO - current website is anhuizhaobiao_sheng_1_23_0
2019-11-28 05:57:31,839 - webcrawer service - INFO - 运行成功: anhuizhaobiao_sheng_1_23_0, 一共：0条
2019-11-28 05:57:31,839 - webcrawer service - INFO - current website is anhuizhaobiao_shixian_1_23_0
2019-11-28 05:57:52,276 - webcrawer service - INFO - 运行成功: anhuizhaobiao_shixian_1_23_0, 一共：0条
2019-11-28 05:57:52,277 - webcrawer service - INFO - current website is anhuizhaobiao_shixian_1_23_1
2019-11-28 05:58:11,249 - webcrawer service - INFO - 运行成功: anhuizhaobiao_shixian_1_23_1, 一共：0条
2019-11-28 05:58:11,250 - webcrawer service - INFO - current website is jiangxijidianshebeizhaobiao_1_24_0
2019-11-28 05:58:27,504 - webcrawer service - INFO - 运行成功: jiangxijidianshebeizhaobiao_1_24_0, 一共：0条
2019-11-28 05:58:27,504 - webcrawer service - INFO - current website is jiangxijidianshebeizhaobiao_1_24_1
2019-11-28 05:58:54,613 - webcrawer service - INFO - 运行成功: jiangxijidianshebeizhaobiao_1_24_1, 一共：1条
2019-11-28 05:58:54,613 - webcrawer service - INFO - current website is guizhoushenggongongziyuanjiaoyi_1_25_0
2019-11-28 05:59:38,652 - webcrawer service - INFO - 运行成功: guizhoushenggongongziyuanjiaoyi_1_25_0, 一共：2条
2019-11-28 05:59:38,652 - webcrawer service - INFO - current website is guizhoushenggongongziyuanjiaoyi_1_25_1
2019-11-28 06:00:13,535 - webcrawer service - INFO - 运行成功: guizhoushenggongongziyuanjiaoyi_1_25_1, 一共：1条
2019-11-28 06:00:13,535 - webcrawer service - INFO - current website is yunnanshenggonggongziyuan_zhengfu_1_26_0
2019-11-28 06:00:45,405 - webcrawer service - INFO - 运行成功: yunnanshenggonggongziyuan_zhengfu_1_26_0, 一共：1条
2019-11-28 06:00:45,405 - webcrawer service - INFO - current website is yunnanshenggonggongziyuan_zhengfu_1_26_1
2019-11-28 06:01:02,456 - webcrawer service - INFO - 运行成功: yunnanshenggonggongziyuan_zhengfu_1_26_1, 一共：0条
2019-11-28 06:01:02,456 - webcrawer service - INFO - current website is chongqingshizhengfucaigou_1_27_0
2019-11-28 06:01:40,373 - webcrawer service - ERROR - 运行失败: chongqingshizhengfucaigou_1_27_0
2019-11-28 06:01:40,374 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 151, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 146, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 74, in getUrlList
    html_str = model.parse_url("",url_type=original_url,url_params=tmp_parame)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 264, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='notice']/div/div[3]/div[3]/ul/li/a[text()=6]"}
  (Session info: headless chrome=76.0.3809.87)


2019-11-28 06:01:40,376 - webcrawer service - INFO - current website is chongqingshizhengfucaigou_1_27_1
2019-11-28 06:02:26,257 - webcrawer service - ERROR - 运行失败: chongqingshizhengfucaigou_1_27_1
2019-11-28 06:02:26,257 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 151, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 146, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 74, in getUrlList
    html_str = model.parse_url("",url_type=original_url,url_params=tmp_parame)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 264, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='notice']/div/div[3]/div[3]/ul/li/a[text()=6]"}
  (Session info: headless chrome=76.0.3809.87)


2019-11-28 06:02:26,258 - webcrawer service - INFO - current website is zizangzizhiquzhengfucaigou_1_28_0
2019-11-28 06:02:59,030 - webcrawer service - INFO - 运行成功: zizangzizhiquzhengfucaigou_1_28_0, 一共：1条
2019-11-28 06:02:59,030 - webcrawer service - INFO - current website is shanxicaigouyuzhaobiao_1_30_0
2019-11-28 06:03:33,212 - webcrawer service - INFO - 运行成功: shanxicaigouyuzhaobiao_1_30_0, 一共：2条
2019-11-28 06:03:33,212 - webcrawer service - INFO - current website is shanxicaigouyuzhaobiao_1_30_1
2019-11-28 06:03:48,968 - webcrawer service - INFO - 运行成功: shanxicaigouyuzhaobiao_1_30_1, 一共：0条
2019-11-28 06:03:48,968 - webcrawer service - INFO - current website is gansuzhaobiao_1_31_0
2019-11-28 06:04:26,888 - webcrawer service - INFO - 运行成功: gansuzhaobiao_1_31_0, 一共：0条
2019-11-28 06:04:26,889 - webcrawer service - INFO - current website is gansuzhaobiao_1_31_1
2019-11-28 06:05:05,111 - webcrawer service - INFO - 运行成功: gansuzhaobiao_1_31_1, 一共：0条
2019-11-28 06:05:05,111 - webcrawer service - INFO - current website is xinjiangzhengfucaigou_1_32_0
2019-11-28 06:05:38,551 - webcrawer service - INFO - 运行成功: xinjiangzhengfucaigou_1_32_0, 一共：1条
2019-11-28 06:05:38,551 - webcrawer service - INFO - current website is xinjiangzhengfucaigou_1_32_1
2019-11-28 06:06:32,754 - webcrawer service - INFO - 运行成功: xinjiangzhengfucaigou_1_32_1, 一共：2条
2019-11-28 06:06:32,755 - webcrawer service - INFO - current website is sichuanzhaobiaocaigou_1_29_0
2019-11-28 06:07:10,926 - webcrawer service - INFO - 运行成功: sichuanzhaobiaocaigou_1_29_0, 一共：0条
2019-11-28 06:07:10,926 - webcrawer service - INFO - current website is sichuanzhaobiaocaigouxinxi_1_29_1
2019-11-28 06:07:33,960 - webcrawer service - INFO - 运行成功: sichuanzhaobiaocaigouxinxi_1_29_1, 一共：0条
2019-11-28 13:03:54,020 - webcrawer service - INFO - current website is jincai_1
2019-11-28 13:08:27,393 - webcrawer service - INFO - current website is jincai_1
2019-11-28 13:10:19,148 - webcrawer service - INFO - 运行成功: jincai_1, 一共：30条
2019-11-28 13:10:19,148 - webcrawer service - INFO - current website is zhongguozhaobiaoyucaigouwang_3
2019-11-29 00:00:05,173 - webcrawer service - INFO - current website is jincai_1
2019-11-29 00:01:53,365 - webcrawer service - INFO - 运行成功: jincai_1, 一共：27条
2019-11-29 00:01:53,365 - webcrawer service - INFO - current website is zhongguozhaobiaoyucaigouwang_3
2019-11-29 03:32:09,216 - webcrawer service - INFO - 运行成功: zhongguozhaobiaoyucaigouwang_3, 一共：3401条
2019-11-29 03:32:09,217 - webcrawer service - INFO - current website is zhongguozhengfucaigouwang_4
2019-11-29 03:41:43,242 - webcrawer service - INFO - 运行成功: zhongguozhengfucaigouwang_4, 一共：71条
2019-11-29 03:41:43,243 - webcrawer service - INFO - current website is zhongguoyidongcaigouyuzhaobiao_5_0
2019-11-29 03:42:32,588 - webcrawer service - INFO - 运行成功: zhongguoyidongcaigouyuzhaobiao_5_0, 一共：6条
2019-11-29 03:42:32,588 - webcrawer service - INFO - current website is guodianzhaobiaowang_7_0
2019-11-29 03:42:44,445 - webcrawer service - INFO - 运行成功: guodianzhaobiaowang_7_0, 一共：0条
2019-11-29 03:42:44,446 - webcrawer service - INFO - current website is beijingshizhengfu_8
2019-11-29 03:44:50,693 - webcrawer service - INFO - 运行成功: beijingshizhengfu_8, 一共：10条
2019-11-29 03:44:50,694 - webcrawer service - INFO - current website is zhonghuazhaobiao_9_0
2019-11-29 03:45:45,625 - webcrawer service - INFO - 运行成功: zhonghuazhaobiao_9_0, 一共：5条
2019-11-29 03:45:45,626 - webcrawer service - INFO - current website is renbao_10
2019-11-29 03:45:58,003 - webcrawer service - INFO - 运行成功: renbao_10, 一共：0条
2019-11-29 03:45:58,003 - webcrawer service - INFO - current website is guoshou_11
2019-11-29 03:46:09,185 - webcrawer service - INFO - 运行成功: guoshou_11, 一共：0条
2019-11-29 03:46:09,186 - webcrawer service - INFO - current website is anbang_12
2019-11-29 03:46:20,574 - webcrawer service - INFO - 运行成功: anbang_12, 一共：0条
2019-11-29 03:46:20,575 - webcrawer service - INFO - current website is taikang_13_0
2019-11-29 03:46:31,893 - webcrawer service - INFO - 运行成功: taikang_13_0, 一共：0条
2019-11-29 03:46:31,894 - webcrawer service - INFO - current website is changchengzichan_14
2019-11-29 03:46:47,264 - webcrawer service - INFO - 运行成功: changchengzichan_14, 一共：0条
2019-11-29 03:46:47,264 - webcrawer service - INFO - current website is xindazichan_15
2019-11-29 03:47:03,420 - webcrawer service - INFO - 运行成功: xindazichan_15, 一共：0条
2019-11-29 03:47:03,420 - webcrawer service - INFO - current website is yangguangbaoxian_16
2019-11-29 03:47:14,283 - webcrawer service - INFO - 运行成功: yangguangbaoxian_16, 一共：0条
2019-11-29 03:47:14,283 - webcrawer service - INFO - current website is chukouxinyongbaoxian_17
2019-11-29 03:47:47,628 - webcrawer service - INFO - 运行成功: chukouxinyongbaoxian_17, 一共：2条
2019-11-29 03:47:47,629 - webcrawer service - INFO - current website is huahai_18
2019-11-29 03:47:59,506 - webcrawer service - INFO - 运行成功: huahai_18, 一共：0条
2019-11-29 03:47:59,507 - webcrawer service - INFO - current website is zhongxinzhaobiao_19
2019-11-29 03:48:29,531 - webcrawer service - INFO - 运行成功: zhongxinzhaobiao_19, 一共：1条
2019-11-29 03:48:29,531 - webcrawer service - INFO - current website is zhongzhenxinxi_20
2019-11-29 03:48:40,863 - webcrawer service - INFO - 运行成功: zhongzhenxinxi_20, 一共：0条
2019-11-29 03:48:40,863 - webcrawer service - INFO - current website is guojiadianwang_21
2019-11-29 03:48:56,636 - webcrawer service - INFO - 运行成功: guojiadianwang_21, 一共：0条
2019-11-29 03:48:56,636 - webcrawer service - INFO - current website is guohang_22
2019-11-29 03:49:12,756 - webcrawer service - INFO - 运行成功: guohang_22, 一共：0条
2019-11-29 03:49:12,757 - webcrawer service - INFO - current website is youzheng_23_0
2019-11-29 03:49:41,492 - webcrawer service - INFO - 运行成功: youzheng_23_0, 一共：1条
2019-11-29 03:49:41,492 - webcrawer service - INFO - current website is tieta_24
2019-11-29 03:49:55,243 - webcrawer service - INFO - 运行成功: tieta_24, 一共：0条
2019-11-29 03:49:55,243 - webcrawer service - INFO - current website is zhongguodianzijinchukou_26
2019-11-29 03:50:06,962 - webcrawer service - INFO - 运行成功: zhongguodianzijinchukou_26, 一共：0条
2019-11-29 03:50:06,962 - webcrawer service - INFO - current website is zhongguodianwangzhucexinxi_27
2019-11-29 03:50:34,453 - webcrawer service - INFO - 运行成功: zhongguodianwangzhucexinxi_27, 一共：1条
2019-11-29 03:50:34,454 - webcrawer service - INFO - current website is chengEzhaobiao_28
2019-11-29 03:51:30,471 - webcrawer service - INFO - 运行成功: chengEzhaobiao_28, 一共：8条
2019-11-29 03:51:30,472 - webcrawer service - INFO - current website is neimengguzhaobiao_29_0
2019-11-29 03:51:42,689 - webcrawer service - INFO - 运行成功: neimengguzhaobiao_29_0, 一共：0条
2019-11-29 03:51:42,690 - webcrawer service - INFO - current website is zhonghuashangwupingtai_1_1_0
2019-11-29 03:52:32,605 - webcrawer service - INFO - 运行成功: zhonghuashangwupingtai_1_1_0, 一共：5条
2019-11-29 03:52:32,605 - webcrawer service - INFO - current website is zhonghuashangwupingtai_1_1_1
2019-11-29 03:53:07,694 - webcrawer service - INFO - 运行成功: zhonghuashangwupingtai_1_1_1, 一共：2条
2019-11-29 03:53:07,695 - webcrawer service - INFO - current website is zhongguorenminbaoxiancaigou_1_3_0
2019-11-29 03:53:19,882 - webcrawer service - INFO - 运行成功: zhongguorenminbaoxiancaigou_1_3_0, 一共：0条
2019-11-29 03:53:19,882 - webcrawer service - INFO - current website is qinglima_1_4_0
2019-11-29 03:57:58,409 - webcrawer service - INFO - 运行成功: qinglima_1_4_0, 一共：39条
2019-11-29 03:57:58,409 - webcrawer service - INFO - current website is qinglima_1_4_1
2019-11-29 03:58:25,900 - webcrawer service - INFO - 运行成功: qinglima_1_4_1, 一共：0条
2019-11-29 03:58:25,900 - webcrawer service - INFO - current website is shandongcaigouyuzhaobiao_1_6_0
2019-11-29 03:59:21,113 - webcrawer service - INFO - 运行成功: shandongcaigouyuzhaobiao_1_6_0, 一共：4条
2019-11-29 03:59:21,114 - webcrawer service - INFO - current website is shandongcaigouyuzhaobiao_1_6_1
2019-11-29 04:00:05,902 - webcrawer service - INFO - 运行成功: shandongcaigouyuzhaobiao_1_6_1, 一共：3条
2019-11-29 04:00:05,903 - webcrawer service - INFO - current website is shanxishenzhaobiaogonggongfuwupingtai_1_7_0
2019-11-29 04:01:53,902 - webcrawer service - INFO - 运行成功: shanxishenzhaobiaogonggongfuwupingtai_1_7_0, 一共：11条
2019-11-29 04:01:53,902 - webcrawer service - INFO - current website is shanxishenzhaobiaogonggongfuwupingtai_1_7_1
2019-11-29 04:02:53,927 - webcrawer service - INFO - 运行成功: shanxishenzhaobiaogonggongfuwupingtai_1_7_1, 一共：6条
2019-11-29 04:02:53,927 - webcrawer service - INFO - current website is zhongyuanzhaocai_1_8_0
2019-11-29 04:03:21,630 - webcrawer service - INFO - 运行成功: zhongyuanzhaocai_1_8_0, 一共：0条
2019-11-29 04:03:21,631 - webcrawer service - INFO - current website is zhongyuanzhaocai_1_8_1
2019-11-29 04:03:47,955 - webcrawer service - INFO - 运行成功: zhongyuanzhaocai_1_8_1, 一共：0条
2019-11-29 04:03:47,956 - webcrawer service - INFO - current website is heibeishenzhaobiaotoubiao_1_9_0
2019-11-29 04:05:02,013 - webcrawer service - INFO - 运行成功: heibeishenzhaobiaotoubiao_1_9_0, 一共：10条
2019-11-29 04:05:02,013 - webcrawer service - INFO - current website is heibeishengzhaobiaotoubiao_1_9_1
2019-11-29 04:05:48,903 - webcrawer service - INFO - 运行成功: heibeishengzhaobiaotoubiao_1_9_1, 一共：4条
2019-11-29 04:05:48,903 - webcrawer service - INFO - current website is heilongjiangcaigou_1_10_0
2019-11-29 04:06:18,504 - webcrawer service - INFO - 运行成功: heilongjiangcaigou_1_10_0, 一共：0条
2019-11-29 04:06:18,504 - webcrawer service - INFO - current website is jilinzhaobiao_1_11_0
2019-11-29 04:06:58,217 - webcrawer service - INFO - 运行成功: jilinzhaobiao_1_11_0, 一共：0条
2019-11-29 04:06:58,217 - webcrawer service - INFO - current website is jilinzhaobiao_1_11_1
2019-11-29 04:07:35,782 - webcrawer service - INFO - 运行成功: jilinzhaobiao_1_11_1, 一共：0条
2019-11-29 04:07:35,782 - webcrawer service - INFO - current website is liaoningzhaobiao_1_12_0
2019-11-29 04:14:51,116 - webcrawer service - INFO - 运行成功: liaoningzhaobiao_1_12_0, 一共：32条
2019-11-29 04:14:51,116 - webcrawer service - INFO - current website is liaoningzhaobiao_1_12_1
2019-11-29 04:22:28,080 - webcrawer service - INFO - 运行成功: liaoningzhaobiao_1_12_1, 一共：12条
2019-11-29 04:22:28,080 - webcrawer service - INFO - current website is dalianzhaobiao_1_13_0
2019-11-29 04:25:11,435 - webcrawer service - INFO - 运行成功: dalianzhaobiao_1_13_0, 一共：12条
2019-11-29 04:25:11,435 - webcrawer service - INFO - current website is dalianzhaobiao_1_13_1
2019-11-29 04:26:57,763 - webcrawer service - INFO - 运行成功: dalianzhaobiao_1_13_1, 一共：4条
2019-11-29 04:26:57,763 - webcrawer service - INFO - current website is shanghaizhaobiao_1_14_0
2019-11-29 04:27:35,433 - webcrawer service - INFO - 运行成功: shanghaizhaobiao_1_14_0, 一共：0条
2019-11-29 04:27:35,433 - webcrawer service - INFO - current website is shanghaizhaobiao_1_14_1
2019-11-29 04:28:12,879 - webcrawer service - INFO - 运行成功: shanghaizhaobiao_1_14_1, 一共：0条
2019-11-29 04:28:12,880 - webcrawer service - INFO - current website is zhejiangzhaobiao_1_15_0
2019-11-29 04:28:50,418 - webcrawer service - INFO - 运行成功: zhejiangzhaobiao_1_15_0, 一共：0条
2019-11-29 04:28:50,418 - webcrawer service - INFO - current website is zhejiangzhaobiao_1_15_1
2019-11-29 04:29:27,899 - webcrawer service - INFO - 运行成功: zhejiangzhaobiao_1_15_1, 一共：0条
2019-11-29 04:29:27,900 - webcrawer service - INFO - current website is jiangsuzhaobiao_1_16_0
2019-11-29 04:30:05,447 - webcrawer service - INFO - 运行成功: jiangsuzhaobiao_1_16_0, 一共：0条
2019-11-29 04:30:05,447 - webcrawer service - INFO - current website is jiangsuzhaobiao_1_16_1
2019-11-29 04:30:42,717 - webcrawer service - INFO - 运行成功: jiangsuzhaobiao_1_16_1, 一共：0条
2019-11-29 04:30:42,718 - webcrawer service - INFO - current website is guangdongshenzhengfucaigou_1_17_0
2019-11-29 04:33:42,673 - webcrawer service - INFO - 运行成功: guangdongshenzhengfucaigou_1_17_0, 一共：8条
2019-11-29 04:33:42,673 - webcrawer service - INFO - current website is guangdongshenzhengfucaigou_1_17_1
2019-11-29 04:37:36,778 - webcrawer service - INFO - 运行成功: guangdongshenzhengfucaigou_1_17_1, 一共：13条
2019-11-29 04:37:36,778 - webcrawer service - INFO - current website is neimengguzizhiquzhengfucaigou
2019-11-29 04:38:53,261 - webcrawer service - INFO - 运行成功: neimengguzizhiquzhengfucaigou, 一共：3条
2019-11-29 04:38:53,262 - webcrawer service - INFO - current website is neimengguzizhiquzhengfucaigou_1
2019-11-29 04:39:09,857 - webcrawer service - ERROR - 运行失败: neimengguzizhiquzhengfucaigou_1
2019-11-29 04:39:09,883 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 151, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 147, in RunMain
    html_str = model.parse_url("",url_type=url_info["type"],url_params=url_info)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 298, in parse_url
    params= url_param["params"]
KeyError: 'params'

2019-11-29 04:39:09,883 - webcrawer service - INFO - current website is fujianshengonggongziyuanjiaoyi_1_18_0
2019-11-29 04:39:42,548 - webcrawer service - INFO - 运行成功: fujianshengonggongziyuanjiaoyi_1_18_0, 一共：0条
2019-11-29 04:39:42,549 - webcrawer service - INFO - current website is guangxizhaobiao_1_19_0
2019-11-29 04:39:58,609 - webcrawer service - INFO - 运行成功: guangxizhaobiao_1_19_0, 一共：0条
2019-11-29 04:39:58,609 - webcrawer service - INFO - current website is guangxizhaobiao_1_19_1
2019-11-29 04:40:14,543 - webcrawer service - INFO - 运行成功: guangxizhaobiao_1_19_1, 一共：0条
2019-11-29 04:40:14,543 - webcrawer service - INFO - current website is hainanzhaobiao_1_20_0
2019-11-29 04:43:03,163 - webcrawer service - INFO - 运行成功: hainanzhaobiao_1_20_0, 一共：10条
2019-11-29 04:43:03,163 - webcrawer service - INFO - current website is hainanzhaobiao_1_20_1
2019-11-29 04:45:24,158 - webcrawer service - INFO - 运行成功: hainanzhaobiao_1_20_1, 一共：2条
2019-11-29 04:45:24,159 - webcrawer service - INFO - current website is shenzhenshiguojizhaobiao_1_21_0
2019-11-29 04:46:08,687 - webcrawer service - INFO - 运行成功: shenzhenshiguojizhaobiao_1_21_0, 一共：1条
2019-11-29 04:46:08,687 - webcrawer service - INFO - current website is shenzhenshiguojizhaobiao_1_21_1
2019-11-29 04:46:38,717 - webcrawer service - INFO - 运行成功: shenzhenshiguojizhaobiao_1_21_1, 一共：1条
2019-11-29 04:46:38,717 - webcrawer service - INFO - current website is hunanxiangzigongchengzixu_1_22_0
2019-11-29 04:46:57,500 - webcrawer service - INFO - 运行成功: hunanxiangzigongchengzixu_1_22_0, 一共：0条
2019-11-29 04:46:57,500 - webcrawer service - INFO - current website is hunanxiangzigongchengzixu_1_22_1
2019-11-29 04:47:16,067 - webcrawer service - INFO - 运行成功: hunanxiangzigongchengzixu_1_22_1, 一共：0条
2019-11-29 04:47:16,067 - webcrawer service - INFO - current website is anhuizhaobiao_sheng_1_23_0
2019-11-29 04:47:29,519 - webcrawer service - INFO - 运行成功: anhuizhaobiao_sheng_1_23_0, 一共：0条
2019-11-29 04:47:29,520 - webcrawer service - INFO - current website is anhuizhaobiao_shixian_1_23_0
2019-11-29 04:48:10,508 - webcrawer service - INFO - 运行成功: anhuizhaobiao_shixian_1_23_0, 一共：1条
2019-11-29 04:48:10,508 - webcrawer service - INFO - current website is anhuizhaobiao_shixian_1_23_1
2019-11-29 04:48:23,150 - webcrawer service - INFO - 运行成功: anhuizhaobiao_shixian_1_23_1, 一共：0条
2019-11-29 04:48:23,151 - webcrawer service - INFO - current website is jiangxijidianshebeizhaobiao_1_24_0
2019-11-29 04:48:50,440 - webcrawer service - INFO - 运行成功: jiangxijidianshebeizhaobiao_1_24_0, 一共：1条
2019-11-29 04:48:50,441 - webcrawer service - INFO - current website is jiangxijidianshebeizhaobiao_1_24_1
2019-11-29 04:49:06,503 - webcrawer service - INFO - 运行成功: jiangxijidianshebeizhaobiao_1_24_1, 一共：0条
2019-11-29 04:49:06,504 - webcrawer service - INFO - current website is guizhoushenggongongziyuanjiaoyi_1_25_0
2019-11-29 04:49:44,661 - webcrawer service - INFO - 运行成功: guizhoushenggongongziyuanjiaoyi_1_25_0, 一共：2条
2019-11-29 04:49:44,661 - webcrawer service - INFO - current website is guizhoushenggongongziyuanjiaoyi_1_25_1
2019-11-29 04:50:07,576 - webcrawer service - INFO - 运行成功: guizhoushenggongongziyuanjiaoyi_1_25_1, 一共：0条
2019-11-29 04:50:07,576 - webcrawer service - INFO - current website is yunnanshenggonggongziyuan_zhengfu_1_26_0
2019-11-29 04:50:24,856 - webcrawer service - INFO - 运行成功: yunnanshenggonggongziyuan_zhengfu_1_26_0, 一共：0条
2019-11-29 04:50:24,857 - webcrawer service - INFO - current website is yunnanshenggonggongziyuan_zhengfu_1_26_1
2019-11-29 04:50:41,825 - webcrawer service - INFO - 运行成功: yunnanshenggonggongziyuan_zhengfu_1_26_1, 一共：0条
2019-11-29 04:50:41,826 - webcrawer service - INFO - current website is chongqingshizhengfucaigou_1_27_0
2019-11-29 04:51:21,376 - webcrawer service - ERROR - 运行失败: chongqingshizhengfucaigou_1_27_0
2019-11-29 04:51:21,505 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 151, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 148, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 76, in getUrlList
    html_str = model.parse_url("",url_type=original_url,url_params=tmp_parame)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 303, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='notice']/div/div[3]/div[3]/ul/li/a[text()=6]"}
  (Session info: headless chrome=76.0.3809.87)


2019-11-29 04:51:21,506 - webcrawer service - INFO - current website is chongqingshizhengfucaigou_1_27_1
2019-11-29 04:52:06,023 - webcrawer service - ERROR - 运行失败: chongqingshizhengfucaigou_1_27_1
2019-11-29 04:52:06,024 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline_test.py", line 151, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 148, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 76, in getUrlList
    html_str = model.parse_url("",url_type=original_url,url_params=tmp_parame)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 303, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='notice']/div/div[3]/div[3]/ul/li/a[text()=6]"}
  (Session info: headless chrome=76.0.3809.87)


2019-11-29 04:52:06,025 - webcrawer service - INFO - current website is zizangzizhiquzhengfucaigou_1_28_0
2019-11-29 04:52:38,648 - webcrawer service - INFO - 运行成功: zizangzizhiquzhengfucaigou_1_28_0, 一共：1条
2019-11-29 04:52:38,648 - webcrawer service - INFO - current website is shanxicaigouyuzhaobiao_1_30_0
2019-11-29 04:53:13,643 - webcrawer service - INFO - 运行成功: shanxicaigouyuzhaobiao_1_30_0, 一共：2条
2019-11-29 04:53:13,644 - webcrawer service - INFO - current website is shanxicaigouyuzhaobiao_1_30_1
2019-11-29 04:53:29,277 - webcrawer service - INFO - 运行成功: shanxicaigouyuzhaobiao_1_30_1, 一共：0条
2019-11-29 04:53:29,277 - webcrawer service - INFO - current website is gansuzhaobiao_1_31_0
2019-11-29 04:54:06,619 - webcrawer service - INFO - 运行成功: gansuzhaobiao_1_31_0, 一共：0条
2019-11-29 04:54:06,620 - webcrawer service - INFO - current website is gansuzhaobiao_1_31_1
2019-11-29 04:54:44,441 - webcrawer service - INFO - 运行成功: gansuzhaobiao_1_31_1, 一共：0条
2019-11-29 04:54:44,442 - webcrawer service - INFO - current website is xinjiangzhengfucaigou_1_32_0
2019-11-29 04:55:23,501 - webcrawer service - INFO - 运行成功: xinjiangzhengfucaigou_1_32_0, 一共：2条
2019-11-29 04:55:23,501 - webcrawer service - INFO - current website is xinjiangzhengfucaigou_1_32_1
2019-11-29 04:56:16,572 - webcrawer service - INFO - 运行成功: xinjiangzhengfucaigou_1_32_1, 一共：4条
2019-11-29 04:56:16,572 - webcrawer service - INFO - current website is sichuanzhaobiaocaigou_1_29_0
2019-11-29 04:56:51,576 - webcrawer service - INFO - 运行成功: sichuanzhaobiaocaigou_1_29_0, 一共：0条
2019-11-29 04:56:51,576 - webcrawer service - INFO - current website is sichuanzhaobiaocaigouxinxi_1_29_1
2019-11-29 04:57:14,146 - webcrawer service - INFO - 运行成功: sichuanzhaobiaocaigouxinxi_1_29_1, 一共：0条
2019-11-29 11:05:45,341 - webcrawer service - INFO - current website is jincai_1
2019-11-29 11:06:24,001 - webcrawer service - INFO - current website is jincai_1
2019-11-29 11:08:04,178 - webcrawer service - INFO - 运行成功: jincai_1, 一共：27条
2019-11-29 11:08:04,178 - webcrawer service - INFO - current website is zhongguozhengfucaigouwang_4
2019-11-29 11:16:02,105 - webcrawer service - INFO - 运行成功: zhongguozhengfucaigouwang_4, 一共：62条
2019-11-29 11:16:02,105 - webcrawer service - INFO - current website is zhongguoyidongcaigouyuzhaobiao_5_0
2019-11-29 11:16:56,515 - webcrawer service - INFO - 运行成功: zhongguoyidongcaigouyuzhaobiao_5_0, 一共：6条
2019-11-29 11:16:56,515 - webcrawer service - INFO - current website is guodianzhaobiaowang_7_0
2019-11-29 11:17:11,498 - webcrawer service - INFO - 运行成功: guodianzhaobiaowang_7_0, 一共：0条
2019-11-29 11:17:11,499 - webcrawer service - INFO - current website is beijingshizhengfu_8
2019-11-29 11:19:27,854 - webcrawer service - INFO - 运行成功: beijingshizhengfu_8, 一共：10条
2019-11-29 11:19:27,855 - webcrawer service - INFO - current website is zhonghuazhaobiao_9_0
2019-11-29 11:20:15,088 - webcrawer service - INFO - 运行成功: zhonghuazhaobiao_9_0, 一共：5条
2019-11-29 11:20:15,089 - webcrawer service - INFO - current website is renbao_10
2019-11-29 11:20:32,787 - webcrawer service - INFO - 运行成功: renbao_10, 一共：0条
2019-11-29 11:20:32,788 - webcrawer service - INFO - current website is guoshou_11
2019-11-29 11:20:47,750 - webcrawer service - INFO - 运行成功: guoshou_11, 一共：0条
2019-11-29 11:20:47,751 - webcrawer service - INFO - current website is anbang_12
2019-11-29 11:21:00,838 - webcrawer service - INFO - 运行成功: anbang_12, 一共：0条
2019-11-29 11:21:00,838 - webcrawer service - INFO - current website is taikang_13_0
2019-11-29 11:21:15,668 - webcrawer service - INFO - 运行成功: taikang_13_0, 一共：0条
2019-11-29 11:21:15,669 - webcrawer service - INFO - current website is changchengzichan_14
2019-11-29 11:21:46,010 - webcrawer service - INFO - 运行成功: changchengzichan_14, 一共：0条
2019-11-29 11:21:46,011 - webcrawer service - INFO - current website is xindazichan_15
2019-11-29 11:22:38,364 - webcrawer service - INFO - 运行成功: xindazichan_15, 一共：0条
2019-11-29 11:22:38,365 - webcrawer service - INFO - current website is yangguangbaoxian_16
2019-11-29 11:22:49,969 - webcrawer service - INFO - 运行成功: yangguangbaoxian_16, 一共：0条
2019-11-29 11:22:49,969 - webcrawer service - INFO - current website is chukouxinyongbaoxian_17
2019-11-29 11:23:33,435 - webcrawer service - INFO - 运行成功: chukouxinyongbaoxian_17, 一共：2条
2019-11-29 11:23:33,436 - webcrawer service - INFO - current website is huahai_18
2019-11-29 11:23:48,520 - webcrawer service - INFO - 运行成功: huahai_18, 一共：0条
2019-11-29 11:23:48,521 - webcrawer service - INFO - current website is zhongxinzhaobiao_19
2019-11-29 11:24:20,065 - webcrawer service - INFO - 运行成功: zhongxinzhaobiao_19, 一共：1条
2019-11-29 11:24:20,065 - webcrawer service - INFO - current website is zhongzhenxinxi_20
2019-11-29 11:24:37,584 - webcrawer service - INFO - 运行成功: zhongzhenxinxi_20, 一共：0条
2019-11-29 11:24:37,584 - webcrawer service - INFO - current website is guojiadianwang_21
2019-11-29 11:24:57,723 - webcrawer service - INFO - 运行成功: guojiadianwang_21, 一共：0条
2019-11-29 11:24:57,723 - webcrawer service - INFO - current website is guohang_22
2019-11-29 11:25:17,999 - webcrawer service - INFO - 运行成功: guohang_22, 一共：0条
2019-11-29 11:25:17,999 - webcrawer service - INFO - current website is youzheng_23_0
2019-11-29 11:25:50,455 - webcrawer service - INFO - 运行成功: youzheng_23_0, 一共：1条
2019-11-29 11:25:50,455 - webcrawer service - INFO - current website is tieta_24
2019-11-29 11:26:05,006 - webcrawer service - INFO - 运行成功: tieta_24, 一共：0条
2019-11-29 11:26:05,006 - webcrawer service - INFO - current website is zhongguodianzijinchukou_26
2019-11-29 11:26:17,072 - webcrawer service - INFO - 运行成功: zhongguodianzijinchukou_26, 一共：0条
2019-11-29 11:26:17,072 - webcrawer service - INFO - current website is zhongguodianwangzhucexinxi_27
2019-11-29 11:26:51,634 - webcrawer service - INFO - 运行成功: zhongguodianwangzhucexinxi_27, 一共：1条
2019-11-29 11:26:51,634 - webcrawer service - INFO - current website is chengEzhaobiao_28
2019-11-29 11:27:53,287 - webcrawer service - INFO - 运行成功: chengEzhaobiao_28, 一共：8条
2019-11-29 11:27:53,287 - webcrawer service - INFO - current website is neimengguzhaobiao_29_0
2019-11-29 11:28:21,556 - webcrawer service - INFO - 运行成功: neimengguzhaobiao_29_0, 一共：0条
2019-11-29 11:28:21,556 - webcrawer service - INFO - current website is zhonghuashangwupingtai_1_1_0
2019-11-29 11:29:17,020 - webcrawer service - INFO - 运行成功: zhonghuashangwupingtai_1_1_0, 一共：5条
2019-11-29 11:29:17,020 - webcrawer service - INFO - current website is zhonghuashangwupingtai_1_1_1
2019-11-29 11:29:59,206 - webcrawer service - INFO - 运行成功: zhonghuashangwupingtai_1_1_1, 一共：2条
2019-11-29 11:29:59,206 - webcrawer service - INFO - current website is zhongguorenminbaoxiancaigou_1_3_0
2019-11-29 11:30:13,320 - webcrawer service - INFO - 运行成功: zhongguorenminbaoxiancaigou_1_3_0, 一共：0条
2019-11-29 11:30:13,320 - webcrawer service - INFO - current website is qinglima_1_4_0
2019-11-29 11:35:02,765 - webcrawer service - INFO - 运行成功: qinglima_1_4_0, 一共：39条
2019-11-29 11:35:02,765 - webcrawer service - INFO - current website is qinglima_1_4_1
2019-11-29 11:35:40,242 - webcrawer service - INFO - 运行成功: qinglima_1_4_1, 一共：0条
2019-11-29 11:35:40,242 - webcrawer service - INFO - current website is shandongcaigouyuzhaobiao_1_6_0
2019-11-29 11:36:51,140 - webcrawer service - INFO - 运行成功: shandongcaigouyuzhaobiao_1_6_0, 一共：4条
2019-11-29 11:36:51,141 - webcrawer service - INFO - current website is shandongcaigouyuzhaobiao_1_6_1
2019-11-29 11:37:40,522 - webcrawer service - INFO - 运行成功: shandongcaigouyuzhaobiao_1_6_1, 一共：3条
2019-11-29 11:37:40,522 - webcrawer service - INFO - current website is shanxishenzhaobiaogonggongfuwupingtai_1_7_0
2019-11-29 11:40:11,698 - webcrawer service - INFO - 运行成功: shanxishenzhaobiaogonggongfuwupingtai_1_7_0, 一共：11条
2019-11-29 11:40:11,699 - webcrawer service - INFO - current website is shanxishenzhaobiaogonggongfuwupingtai_1_7_1
2019-11-29 11:41:31,802 - webcrawer service - INFO - 运行成功: shanxishenzhaobiaogonggongfuwupingtai_1_7_1, 一共：6条
2019-11-29 11:41:31,803 - webcrawer service - INFO - current website is zhongyuanzhaocai_1_8_0
2019-11-29 11:42:01,335 - webcrawer service - INFO - 运行成功: zhongyuanzhaocai_1_8_0, 一共：0条
2019-11-29 11:42:01,335 - webcrawer service - INFO - current website is zhongyuanzhaocai_1_8_1
2019-11-29 11:42:30,690 - webcrawer service - INFO - 运行成功: zhongyuanzhaocai_1_8_1, 一共：0条
2019-11-29 11:42:30,691 - webcrawer service - INFO - current website is heibeishenzhaobiaotoubiao_1_9_0
2019-11-29 11:43:49,936 - webcrawer service - INFO - 运行成功: heibeishenzhaobiaotoubiao_1_9_0, 一共：10条
2019-11-29 11:43:49,936 - webcrawer service - INFO - current website is heibeishengzhaobiaotoubiao_1_9_1
2019-11-29 11:44:40,226 - webcrawer service - INFO - 运行成功: heibeishengzhaobiaotoubiao_1_9_1, 一共：4条
2019-11-29 11:44:40,227 - webcrawer service - INFO - current website is heilongjiangcaigou_1_10_0
2019-11-29 11:45:13,270 - webcrawer service - INFO - 运行成功: heilongjiangcaigou_1_10_0, 一共：0条
2019-11-29 11:45:13,271 - webcrawer service - INFO - current website is jilinzhaobiao_1_11_0
2019-11-29 11:45:54,035 - webcrawer service - INFO - 运行成功: jilinzhaobiao_1_11_0, 一共：0条
2019-11-29 11:45:54,035 - webcrawer service - INFO - current website is jilinzhaobiao_1_11_1
2019-11-29 11:46:33,122 - webcrawer service - INFO - 运行成功: jilinzhaobiao_1_11_1, 一共：0条
2019-11-29 11:46:33,122 - webcrawer service - INFO - current website is liaoningzhaobiao_1_12_0
2019-11-29 11:54:25,121 - webcrawer service - INFO - 运行成功: liaoningzhaobiao_1_12_0, 一共：32条
2019-11-29 11:54:25,122 - webcrawer service - INFO - current website is liaoningzhaobiao_1_12_1
2019-11-29 12:00:06,743 - webcrawer service - INFO - 运行成功: liaoningzhaobiao_1_12_1, 一共：14条
2019-11-29 12:00:06,743 - webcrawer service - INFO - current website is dalianzhaobiao_1_13_0
2019-11-29 12:02:52,561 - webcrawer service - INFO - 运行成功: dalianzhaobiao_1_13_0, 一共：14条
2019-11-29 12:02:52,561 - webcrawer service - INFO - current website is dalianzhaobiao_1_13_1
2019-11-29 12:04:49,730 - webcrawer service - INFO - 运行成功: dalianzhaobiao_1_13_1, 一共：4条
2019-11-29 12:04:49,731 - webcrawer service - INFO - current website is shanghaizhaobiao_1_14_0
2019-11-29 12:05:29,180 - webcrawer service - INFO - 运行成功: shanghaizhaobiao_1_14_0, 一共：0条
2019-11-29 12:05:29,181 - webcrawer service - INFO - current website is shanghaizhaobiao_1_14_1
2019-11-29 12:06:27,734 - webcrawer service - INFO - 运行成功: shanghaizhaobiao_1_14_1, 一共：0条
2019-11-29 12:06:27,734 - webcrawer service - INFO - current website is zhejiangzhaobiao_1_15_0
2019-11-29 12:07:05,416 - webcrawer service - INFO - 运行成功: zhejiangzhaobiao_1_15_0, 一共：0条
2019-11-29 12:07:05,416 - webcrawer service - INFO - current website is zhejiangzhaobiao_1_15_1
2019-11-29 12:07:45,034 - webcrawer service - INFO - 运行成功: zhejiangzhaobiao_1_15_1, 一共：0条
2019-11-29 12:07:45,035 - webcrawer service - INFO - current website is jiangsuzhaobiao_1_16_0
2019-11-29 12:08:24,065 - webcrawer service - INFO - 运行成功: jiangsuzhaobiao_1_16_0, 一共：0条
2019-11-29 12:08:24,066 - webcrawer service - INFO - current website is jiangsuzhaobiao_1_16_1
2019-11-29 12:09:02,456 - webcrawer service - INFO - 运行成功: jiangsuzhaobiao_1_16_1, 一共：0条
2019-11-29 12:09:02,457 - webcrawer service - INFO - current website is guangdongshenzhengfucaigou_1_17_0
2019-11-29 12:10:27,779 - webcrawer service - INFO - 运行成功: guangdongshenzhengfucaigou_1_17_0, 一共：1条
2019-11-29 12:10:27,779 - webcrawer service - INFO - current website is guangdongshenzhengfucaigou_1_17_1
2019-11-29 12:14:16,341 - webcrawer service - INFO - 运行成功: guangdongshenzhengfucaigou_1_17_1, 一共：13条
2019-11-29 12:14:16,342 - webcrawer service - INFO - current website is neimengguzizhiquzhengfucaigou
2019-11-29 12:15:49,481 - webcrawer service - INFO - 运行成功: neimengguzizhiquzhengfucaigou, 一共：3条
2019-11-29 12:15:49,481 - webcrawer service - INFO - current website is neimengguzizhiquzhengfucaigou_1
2019-11-29 12:17:19,464 - webcrawer service - INFO - 运行成功: neimengguzizhiquzhengfucaigou_1, 一共：6条
2019-11-29 12:17:19,464 - webcrawer service - INFO - current website is fujianshengonggongziyuanjiaoyi_1_18_0
2019-11-29 12:18:00,868 - webcrawer service - INFO - 运行成功: fujianshengonggongziyuanjiaoyi_1_18_0, 一共：0条
2019-11-29 12:18:00,869 - webcrawer service - INFO - current website is guangxizhaobiao_1_19_0
2019-11-29 12:18:17,273 - webcrawer service - INFO - 运行成功: guangxizhaobiao_1_19_0, 一共：0条
2019-11-29 12:18:17,274 - webcrawer service - INFO - current website is guangxizhaobiao_1_19_1
2019-11-29 12:18:35,800 - webcrawer service - INFO - 运行成功: guangxizhaobiao_1_19_1, 一共：0条
2019-11-29 12:18:35,800 - webcrawer service - INFO - current website is hainanzhaobiao_1_20_0
2019-11-29 12:21:42,223 - webcrawer service - INFO - 运行成功: hainanzhaobiao_1_20_0, 一共：13条
2019-11-29 12:21:42,224 - webcrawer service - INFO - current website is hainanzhaobiao_1_20_1
2019-11-29 12:23:25,330 - webcrawer service - INFO - 运行成功: hainanzhaobiao_1_20_1, 一共：2条
2019-11-29 12:23:25,330 - webcrawer service - INFO - current website is shenzhenshiguojizhaobiao_1_21_0
2019-11-29 12:24:11,136 - webcrawer service - INFO - 运行成功: shenzhenshiguojizhaobiao_1_21_0, 一共：1条
2019-11-29 12:24:11,136 - webcrawer service - INFO - current website is shenzhenshiguojizhaobiao_1_21_1
2019-11-29 12:24:46,079 - webcrawer service - INFO - 运行成功: shenzhenshiguojizhaobiao_1_21_1, 一共：1条
2019-11-29 12:24:46,079 - webcrawer service - INFO - current website is hunanxiangzigongchengzixu_1_22_0
2019-11-29 12:25:06,514 - webcrawer service - INFO - 运行成功: hunanxiangzigongchengzixu_1_22_0, 一共：0条
2019-11-29 12:25:06,514 - webcrawer service - INFO - current website is hunanxiangzigongchengzixu_1_22_1
2019-11-29 12:25:39,954 - webcrawer service - INFO - 运行成功: hunanxiangzigongchengzixu_1_22_1, 一共：0条
2019-11-29 12:25:39,954 - webcrawer service - INFO - current website is anhuizhaobiao_sheng_1_23_0
2019-11-29 12:25:54,467 - webcrawer service - INFO - 运行成功: anhuizhaobiao_sheng_1_23_0, 一共：0条
2019-11-29 12:25:54,467 - webcrawer service - INFO - current website is anhuizhaobiao_shixian_1_23_0
2019-11-29 12:26:42,735 - webcrawer service - INFO - 运行成功: anhuizhaobiao_shixian_1_23_0, 一共：1条
2019-11-29 12:26:42,735 - webcrawer service - INFO - current website is anhuizhaobiao_shixian_1_23_1
2019-11-29 12:27:02,472 - webcrawer service - INFO - 运行成功: anhuizhaobiao_shixian_1_23_1, 一共：0条
2019-11-29 12:27:02,472 - webcrawer service - INFO - current website is jiangxijidianshebeizhaobiao_1_24_0
2019-11-29 12:27:33,571 - webcrawer service - INFO - 运行成功: jiangxijidianshebeizhaobiao_1_24_0, 一共：1条
2019-11-29 12:27:33,571 - webcrawer service - INFO - current website is jiangxijidianshebeizhaobiao_1_24_1
2019-11-29 12:27:51,180 - webcrawer service - INFO - 运行成功: jiangxijidianshebeizhaobiao_1_24_1, 一共：0条
2019-11-29 12:27:51,180 - webcrawer service - INFO - current website is guizhoushenggongongziyuanjiaoyi_1_25_0
2019-11-29 12:28:30,720 - webcrawer service - INFO - 运行成功: guizhoushenggongongziyuanjiaoyi_1_25_0, 一共：2条
2019-11-29 12:28:30,720 - webcrawer service - INFO - current website is guizhoushenggongongziyuanjiaoyi_1_25_1
2019-11-29 12:28:53,622 - webcrawer service - INFO - 运行成功: guizhoushenggongongziyuanjiaoyi_1_25_1, 一共：0条
2019-11-29 12:28:53,622 - webcrawer service - INFO - current website is yunnanshenggonggongziyuan_zhengfu_1_26_0
2019-11-29 12:29:11,004 - webcrawer service - INFO - 运行成功: yunnanshenggonggongziyuan_zhengfu_1_26_0, 一共：0条
2019-11-29 12:29:11,004 - webcrawer service - INFO - current website is yunnanshenggonggongziyuan_zhengfu_1_26_1
2019-11-29 12:29:29,223 - webcrawer service - INFO - 运行成功: yunnanshenggonggongziyuan_zhengfu_1_26_1, 一共：0条
2019-11-29 12:29:29,223 - webcrawer service - INFO - current website is chongqingshizhengfucaigou_1_27_0
2019-11-29 12:30:11,048 - webcrawer service - ERROR - 运行失败: chongqingshizhengfucaigou_1_27_0
2019-11-29 12:30:11,050 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline.py", line 149, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 148, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 76, in getUrlList
    html_str = model.parse_url("",url_type=original_url,url_params=tmp_parame)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 303, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='notice']/div/div[3]/div[3]/ul/li/a[text()=6]"}
  (Session info: headless chrome=76.0.3809.87)


2019-11-29 12:30:11,051 - webcrawer service - INFO - current website is chongqingshizhengfucaigou_1_27_1
2019-11-29 12:31:00,280 - webcrawer service - ERROR - 运行失败: chongqingshizhengfucaigou_1_27_1
2019-11-29 12:31:00,280 - webcrawer service - ERROR - Traceback (most recent call last):
  File "D:/crawler/Web_crawler/new_Crawler/try_pipeline.py", line 149, in Pipeline
    result = testClass.RunMain(text["original_url"], self.key_array, key,vericode)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 148, in RunMain
    self.getUrlList(model, parame, html_str, original_url,isloopBytime)
  File "D:\crawler\Web_crawler\new_Crawler\test.py", line 76, in getUrlList
    html_str = model.parse_url("",url_type=original_url,url_params=tmp_parame)
  File "D:\crawler\Web_crawler\new_Crawler\CrawlerModule.py", line 303, in parse_url
    self.driver.find_element_by_xpath(url_param["button"]).click()
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yuele\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='notice']/div/div[3]/div[3]/ul/li/a[text()=6]"}
  (Session info: headless chrome=76.0.3809.87)


2019-11-29 12:31:00,281 - webcrawer service - INFO - current website is zizangzizhiquzhengfucaigou_1_28_0
2019-11-29 12:31:43,067 - webcrawer service - INFO - 运行成功: zizangzizhiquzhengfucaigou_1_28_0, 一共：1条
2019-11-29 12:31:43,067 - webcrawer service - INFO - current website is shanxicaigouyuzhaobiao_1_30_0
2019-11-29 12:32:16,187 - webcrawer service - INFO - 运行成功: shanxicaigouyuzhaobiao_1_30_0, 一共：2条
2019-11-29 12:32:16,187 - webcrawer service - INFO - current website is shanxicaigouyuzhaobiao_1_30_1
2019-11-29 12:32:31,674 - webcrawer service - INFO - 运行成功: shanxicaigouyuzhaobiao_1_30_1, 一共：0条
2019-11-29 12:32:31,674 - webcrawer service - INFO - current website is gansuzhaobiao_1_31_0
2019-11-29 12:33:09,725 - webcrawer service - INFO - 运行成功: gansuzhaobiao_1_31_0, 一共：0条
2019-11-29 12:33:09,725 - webcrawer service - INFO - current website is gansuzhaobiao_1_31_1
2019-11-29 12:33:47,681 - webcrawer service - INFO - 运行成功: gansuzhaobiao_1_31_1, 一共：0条
2019-11-29 12:33:47,681 - webcrawer service - INFO - current website is xinjiangzhengfucaigou_1_32_0
2019-11-29 12:34:28,820 - webcrawer service - INFO - 运行成功: xinjiangzhengfucaigou_1_32_0, 一共：2条
2019-11-29 12:34:28,820 - webcrawer service - INFO - current website is xinjiangzhengfucaigou_1_32_1
2019-11-29 12:35:27,817 - webcrawer service - INFO - 运行成功: xinjiangzhengfucaigou_1_32_1, 一共：4条
2019-11-29 12:35:27,817 - webcrawer service - INFO - current website is sichuanzhaobiaocaigou_1_29_0
2019-11-29 12:36:03,775 - webcrawer service - INFO - 运行成功: sichuanzhaobiaocaigou_1_29_0, 一共：0条
2019-11-29 12:36:03,775 - webcrawer service - INFO - current website is sichuanzhaobiaocaigouxinxi_1_29_1
2019-11-29 12:36:26,077 - webcrawer service - INFO - 运行成功: sichuanzhaobiaocaigouxinxi_1_29_1, 一共：0条
2019-11-29 17:36:37,469 - webcrawer service - INFO - current website is jincai_1
2019-11-29 17:37:47,993 - webcrawer service - INFO - current website is huazhongzhaobiaowang_3_8_0
2019-11-29 17:40:52,537 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_0, 一共：21条
2019-11-29 17:40:52,537 - webcrawer service - INFO - current website is huazhongzhaobiaowang_3_8_1
2019-11-29 17:41:28,732 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_1, 一共：0条
2019-11-29 17:41:28,733 - webcrawer service - INFO - current website is shanghaigonggongziyuanjiaoyiwang_3_14
2019-11-29 17:42:01,790 - webcrawer service - INFO - 运行成功: shanghaigonggongziyuanjiaoyiwang_3_14, 一共：0条
2019-11-29 17:47:15,786 - webcrawer service - INFO - current website is huazhongzhaobiaowang_3_8_0
2019-11-29 17:47:46,444 - webcrawer service - INFO - current website is zhongguoyouzheng_3_31_0
2019-11-29 17:48:25,627 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_0, 一共：3条
2019-11-29 17:48:25,627 - webcrawer service - INFO - current website is zhongguoyouzheng_3_31_1
2019-11-29 17:49:19,942 - webcrawer service - INFO - 运行成功: zhongguoyouzheng_3_31_1, 一共：9条
2019-12-03 09:41:57,170 - webcrawer service - INFO - current website is huazhongzhaobiaowang_3_8_1
2019-12-03 09:42:54,697 - webcrawer service - INFO - 运行成功: huazhongzhaobiaowang_3_8_1, 一共：0条
